shakespeare_plays = ["All’s Well That Ends Well",
  "Antony and Cleopatra",
  "As You Like It",
  "The Comedy of Errors",
  "Coriolanus",
  "Cymbeline",
  "Hamlet",
  "Henry IV, Part 1",
  "Henry IV, Part 2",
  "Henry V",
  "Henry VI, Part 1",
  "Henry VI, Part 2",
  "Henry VI, Part 3",
  "Henry VIII",
  "Julius Caesar",
  "King John",
  "King Lear",
  "Love’s Labour’s Lost",
  "Macbeth",
  "Measure for Measure",
  "The Merchant of Venice",
  "The Merry Wives of Windsor",
  "A Midsummer Night’s Dream",
  "Much Ado About Nothing",
  "Othello",
  "Pericles",
  "Richard II",
  "Richard III",
  "Romeo and Juliet",
  "The Taming of the Shrew",
  "The Tempest",
  "Timon of Athens",
  "Titus Andronicus",
  "Troilus and Cressida",
  "Twelfth Night",
  "The Two Gentlemen of Verona",
  "The Two Noble Kinsmen",
  "The Winter’s Tale"]

# items that need capital letters are prefaced with a " " for processing later
google_business_categories = ["Abbey",
  "Aboriginal Art Gallery",
  "Abortion Clinic",
  "Abrasives Supplier",
  " Abundant Life church",
  "Accountant",
  "Accounting Firm",
  "Accounting School",
  "Accounting Software Company",
  "Acoustical Consultant",
  "Acrobatic Diving Pool",
  "Acrylic Store",
  "Acupuncture Clinic",
  "Acupuncture School",
  "Acupuncturist’s",
  "Acura Dealer",
  "Addiction Treatment Center",
  "Administrative Attorney",
  "Adoption Agency",
  "Adult Day Care Center",
  "adult DVD store",
  "Adult Education School",
  "Adult Entertainment Club",
  "Adult Entertainment Store",
  "Adult Foster Care Service",
  "Adventure Sports Center",
  "Advertising Agency",
  "Commercial Photographer",
  "Advertising Service",
  "Aerated Drinks Supplier",
  "Antenna Service",
  "Aerial Photographer",
  "Aerial Sports Center",
  "Aero Dance Class",
  "Aerobics Instructor",
  "Aeroclub",
  "Aeromodel Shop",
  "Aeronautical Engineering firm",
  "Aerospace Company",
  " Afghani restaurant",
  " African goods store",
  " African restaurant",
  "Aggregate Supplier",
  "Agistment Service",
  "Agricultural Association",
  "Agricultural Cooperative",
  "Agricultural Engineering Firm",
  "Agricultural High School",
  "Agricultural Machinery Manufacturer",
  "Agricultural Organization",
  "Agricultural Product Wholesaler",
  "Agricultural Production Firm",
  "Agricultural Service",
  "Agricultural Service Supply Agency",
  "Agriculture Cooperative",
  "Agrochemicals Supplier",
  "Aikido Club",
  "Aikido School",
  "Air Compressor Repair Service",
  "Air Compressor Supplier",
  "Air Conditioning Contractor",
  "Air Conditioning Repair Service",
  "Air Conditioning Store",
  "Air Conditioning System Supplier",
  "Air Duct Cleaning Service",
  "Air Filter Supplier",
  "Air Force Base",
  "Air Taxi Service",
  "Airbrushing Service",
  "Airbrushing Supply Store",
  "Aircraft Maintenance Company",
  "Aircraft Manufacturer",
  "Aircraft Rental Service",
  "Aircraft Supply Store",
  "Airline",
  "Airline Ticket Agency",
  "Airport",
  "Airport Hotel",
  "Airport Shuttle Service",
  "Airsoft Supply Store",
  "Airstrip",
  "Alcohol Manufacturer",
  "Alcohol Retail Monopoly",
  "Alcoholic Beverage Wholesaler",
  "Alcoholism Treatment Program",
  "Allergist’s",
  " Alliance church",
  " Alsatian restaurant",
  "Alternative Fuel Station",
  "Alternative Medicine Practitioner",
  "Alternator Supplier",
  "Aluminum Supplier",
  "Aluminum Frames Supplier",
  "Aluminum Welder",
  "Aluminum Window",
  "Amateur theater group",
  "Ambulance Service",
  " American restaurant",
  " Amish furniture store",
  "Ammunition Supplier",
  "Amphitheater",
  "Amusement Center",
  "Amusement Machine Supplier",
  "Amusement Park",
  "Amusement Ride Supplier",
  " Anhui restaurant",
  "Anago Restaurant",
  " Andalusian restaurant",
  "Anesthesiologist’s",
  "Angler Fish Restaurant",
  " Anglican church",
  "Animal Control Service",
  "Animal Hospital",
  "Animal Park",
  "Animal Protection Organization",
  "Animal Rescue Service",
  "Animal Shelter",
  "Animation Studio",
  "Anime Club",
  "Anodizer service",
  "Antique Furniture Restoration Service",
  "Antique Furniture Store",
  "Antique Store",
  "Apartment Building",
  "Apartment Complex",
  "Apartment Rental Agency",
  " Apostolic church",
  "Appliance Parts Supplier",
  "Appliance Rental Service",
  "Appliance Repair Service",
  "Appliance Store",
  "Appliances Customer Service",
  "Appraisal service",
  "Apprenticeship Center",
  "Aquaculture Farm",
  "Aquarium",
  "Aquarium Shop",
  "Aquatic Centre",
  "Arboretum",
  "Arborist and Tree Surgery practice",
  "Archaeological Museum",
  "Archery Club",
  "Archery Hall",
  "Archery Range",
  "Archery Store",
  "Architects Association",
  "Architectural and Engineering Model Maker",
  "Architectural Designer",
  "Architectural Salvage Store",
  "Architecture Firm",
  "Architecture School",
  "Archive",
  "Arena",
  " Argentinian restaurant",
  "Armed Forces Association",
  " Armenian church",
  " Armenian restaurant",
  "Army and Navy Surplus Shop",
  "Army Barracks",
  "Army Facility",
  "Army Museum",
  "Aromatherapy Class",
  "Aromatherapy Service",
  "Aromatherapy Supply Store",
  "Art Cafe",
  "Art Center",
  "Art Dealer",
  "Art Gallery",
  "Art and Handcraft Store",
  "Art Museum",
  "Art Restoration Service",
  "Art School",
  "Art Studio",
  "Art Supply Store",
  "Artificial Plant Supplier",
  "Artistic Painting School",
  "Arts Organization",
  "Grill",
  "Asbestos Testing Service",
  "Ashram",
  " Asian fusion restaurant",
  " Asian grocery store",
  " Asian household goods store",
  " Asian massage therapist’s",
  " Asian restaurant",
  "Asphalt Contractor",
  "Asphalt Mixing Plant",
  " Assemblies of God church",
  "Assembly Room",
  "Assisted Living Facility",
  "Astrology center",
  " Asturian restaurant",
  "Athletic Club",
  "Athletic Field",
  "Athletic Park",
  "Athletic Track",
  "Attorney Referral Service",
  " ATV dealer",
  " ATV rental service",
  " ATV repair shop",
  "Auction House",
  "Audio Visual Consultant",
  "Audio Visual Equipment Rental Service",
  "Audio Visual Equipment Repair Service",
  "Audio Visual Equipment Supplier",
  "Audiologist’s",
  "Auditing Firm",
  "Auditorium",
  " Australian goods store",
  " Australian restaurant",
  " Austrian restaurant",
  "Auto Accessories Wholesaler",
  "Auto Air Conditioning Service",
  "Auto Auction House",
  "Auto Body Parts Supplier",
  "Auto Body Shop",
  "Auto Broker",
  "Auto Chemistry Shop",
  "Auto Dent Removal Service",
  "Auto Electrical Service",
  "Auto Glass Shop",
  "Auto Insurance Agency",
  "Auto Machine Shop",
  "Auto Market",
  "Auto Parts Manufacturer",
  "Auto Parts Market",
  "Auto Parts Store",
  "Auto Radiator Repair Service",
  "Auto Repair Shop",
  "Auto Restoration Service",
  "Auto Spring Shop",
  "Auto Sunroof Shop",
  "Auto Tag Agency",
  "Auto Tune-Up Service",
  "Auto Upholsterer",
  "Auto Wrecker",
  "Automation Company",
  "Automobile Storage Facility",
  "Aviation Consultant",
  "Aviation Training Institute",
  "Awning Supplier",
  "Baby Clothing Store",
  "Baby Store",
  "Baby Swimming School",
  "Childminder",
  "Badminton Club",
  "Badminton Complex",
  "Badminton Court",
  "Bag Shop",
  "Bagel Shop",
  " Bahá’í house of worship",
  "Bail Bonds Service",
  "Bailiff",
  "Bait Shop",
  "Bakery",
  "Bakery Equipment",
  "Baking Supply Store",
  "Ballet School",
  "Ballet Theater",
  "Balloon Artist service",
  "Balloon Ride Tour Agency",
  "Balloon Store",
  "Ballroom",
  "Ballroom Dance Instructor",
  " Bangladeshi restaurant",
  "Bank",
  "Bankruptcy Attorney firm",
  "Bankruptcy Service",
  "Banner Store",
  "Banquet Hall",
  " Baptist church",
  "Bar",
  "Bar and Grill",
  "Bar Restaurant Furniture Store",
  "Bar Stool Supplier",
  "Bar Tabac",
  "Barbecue Restaurant",
  "Barbecue area",
  "Barber School",
  "Barber Shop",
  "Barber Supply Store",
  "Bark Supplier",
  "Barrel Supplier",
  "Barrister’s firm",
  "Bartending School",
  "Baseball Club",
  "Baseball Field",
  "Baseball Goods Store",
  "Basilica",
  "Basket Supplier",
  "Basketball Club",
  "Basketball Court",
  "Basketball Court Contractor",
  " Basque restaurant",
  "Bathroom Remodeler",
  "Bathroom Supply Store",
  "Battery Manufacturer",
  "Battery Store",
  "Battery Wholesaler",
  "Batting Cage Center",
  "Bazar",
  " BBQ Area",
  "Beach Cleaning Service",
  "Beach Clothing Store",
  "Beach Entertainment Shop",
  "Beach Pavillion",
  "Beach Resort",
  "Beach Volleyball Club",
  "Beach Volleyball Court",
  "Bead Store",
  "Bead Wholesaler",
  "Bearing Supplier",
  "Beauty Product Supplier",
  "Beauty Products Vending Machine",
  "Beauty Products Wholesaler",
  "Beauty Salon",
  "Beauty School",
  "Beauty Supply Store",
  "Bed and Breakfast",
  "Bed Shop",
  "Bedding Store",
  "Bedroom Furniture Store",
  " Gyudon restaurant",
  "Beer Distributor",
  "Beer Garden",
  "Beer Hall",
  "Beer Store",
  "Belgian Restaurant",
  "Belt Shop",
  "Berry Restaurant",
  "Betting Agency",
  "Beverage Distributor",
  " Bible church",
  "Bicycle Club",
  "Bicycle Rack",
  "Bicycle Rental Service",
  "Bicycle Repair Shop",
  "Bike Sharing Station",
  "Bicycle Store",
  "Bicycle Wholesale",
  " Bikram yoga studio",
  "Bilingual School",
  "Billiards Supply Store",
  "Bingo Hall",
  "Biochemical Supplier",
  "Biochemistry Lab",
  "Biofeedback Therapist’s",
  "Biotechnology Company",
  "Biotechnology Engineer",
  "Bird Control Service",
  "Bird Shop",
  "Bird-Watching Area",
  "Birth Center",
  "Birth Certificate Service",
  "Birth Control Center",
  "Bistro",
  "Blacksmith",
  "Blast Cleaning Service",
  "Blind School",
  "Blinds Shop",
  "Blood Bank",
  "Blood Donation Center",
  "Blood Testing Service",
  "Blueprint Service",
  "Blues Club",
  " BMW dealer",
  " BMW motorcycle dealer",
  " BMX club",
  " BMX park",
  " BMX track",
  "Board Game Club",
  "Board of Education",
  "Board of Trade",
  "Boarding House",
  "Boarding School",
  "Boat Accessories Supplier",
  "Boat Builders",
  "Boat Club",
  "Boat Cover Supplier",
  "Boat Dealer",
  "Boat Ramp",
  "Boat Rental Service",
  "Boat Repair Shop",
  "Boat Storage Facility",
  "Boat Tour Agency",
  "Boat Trailer Dealer",
  "Boatel",
  "Boating Instructor",
  " Bocce ball court",
  "Body Piercing Shop",
  "Body Shaping Class",
  "Boiler Manufacturer",
  "Boiler Supplier",
  "Bonesetting House",
  "Bonsai Plant Supplier",
  "Book Publisher",
  "Book Store",
  "Bookbinder",
  "Bookkeeping Service",
  "Bookmaker",
  "Books Wholesaler",
  "Boot Camp",
  "Boot Repair Shop",
  "Boot Store",
  "Border-Crossing Station",
  "Border Guard",
  "Botanical Garden",
  "Bottle and Can Redemption Center",
  "Bottled Water Supplier",
  "Bouncy Castle Rental Service",
  "Boutique",
  "Boutique Hotel",
  "Bowling Alley",
  "Bowling Club",
  "Bowling Supply Shop",
  "Box Lunch Supplier",
  "Boxing Club",
  "Boxing Gym",
  "Boxing Ring",
  "Boys’ High School",
  " BPO company",
  " BPO placement agency",
  "Brake Shop",
  " Brazilian restaurant",
  "Breakfast Restaurant",
  "Brewery",
  "Brewing Supply Store",
  "Brewpub",
  "Brick Manufacturer",
  "Bricklayer",
  "Bridal Shop",
  "Bridge",
  "Bridge Club",
  " British restaurant",
  "brothel",
  "Brunch Restaurant",
  "Bubble Tea store",
  " Buddhist supplies store",
  " Buddhist temple",
  "Budget Hotel",
  " budget Japanese inn",
  "Buffet Restaurant",
  " Buick dealer",
  "Building Consultant",
  "Building Design Company",
  "Building Equipment Hire Service",
  "Building Firm",
  "Building Inspector",
  "Building Materials Market",
  "Building Materials Store",
  "Building Materials Supply firm",
  "Building Restoration Service",
  "Building Society",
  "Chartered Surveyor firm",
  " Bulgarian restaurant",
  "Bullring",
  "Bungee Jumping Center",
  "Burglar Alarm Store",
  " Burmese restaurant",
  "Burrito Restaurant",
  "Bus and Coach Company",
  "Bus Charter company",
  "Bus Company",
  "Bus Ticket Agency",
  "Bus Tour Agency",
  "Business Administration Service",
  "Business Broker",
  "Business Center",
  "Business Development Service",
  "Business Hotel",
  "Business Management Consultant",
  "Business Networking Company",
  "Business Park",
  "Business School",
  "Business-to-Business Service",
  "Butane Gas Supplier",
  "Butcher’s Shop",
  "Butcher Shop Deli",
  "Butsudan store",
  "Cabaret Club",
  "Cabin Rental Agency",
  "Cabinet Maker",
  "Cabinet Store",
  "Cable Company",
  " Cadillac dealer",
  "Cafe",
  "Cafeteria",
  " Cajun restaurant",
  "Cake Decorating Equipment Shop",
  "Cake Shop",
  " Californian restaurant",
  "Call Center",
  "Call Shop",
  "Calligraphy school",
  " Calvary Chapel church",
  " Cambodian restaurant",
  "Camera Repair Shop",
  "Camera Store",
  "Camp",
  "Camper Shell Supplier",
  "Campground",
  "Camping Farm",
  "Camping Store",
  " Pacific Northwest restaurant",
  " Canadian restaurant",
  "Cancer Treatment Center",
  "Candle Store",
  "Candy Store",
  "Cane Furniture Store",
  "Cannabis store",
  "Cannery",
  "Canoe and Kayak Club",
  "Canoe and Kayak Rental Service",
  "Canoe and Kayak Store",
  "Canoe and Kayak Tour Agency",
  "Canoeing Area",
  " Cantabrian restaurant",
  " Cantonese restaurant",
  " Cape Verdean restaurant",
  "Capoeira School",
  "Capsule Hotel",
  "Car Accessories Store",
  "Car Alarm Supplier",
  "Car Battery Store",
  "Car Dealer",
  "Car Detailing Service",
  "Car Factory",
  "Car Finance and Loan Company",
  "Car Inspection Station",
  "Car Leasing Service",
  "Car Manufacturer",
  "Car Racing Track",
  "Car Rental Agency",
  "Car Repair and Maintenance",
  "Car Security System Installer",
  "Car Service",
  "Car Sharing Location",
  "Car Stereo Store",
  "Car Wash",
  "Carabinieri Police station",
  "Cardiologist’s",
  "Career Guidance Service",
  " Caribbean restaurant",
  "Carnival Club",
  "Carpentry firm",
  "Carpet Cleaning Service",
  "Carpet Installer",
  "Carpet Manufacturer",
  "Carpet Store",
  "Carpet Wholesaler",
  "Carpool service",
  "Carport and Pergola Builder",
  "Carriage Ride Service",
  "Carvery",
  "Cash and Carry Wholesaler",
  "Casino",
  "Casket Service",
  " Castilian restaurant",
  "Castle",
  "Castle Hotel",
  "Syokudo and Teishoku Restaurant",
  "Conveyor Belt Sushi Restaurant",
  "Cat Hostel",
  " Catalonian restaurant",
  "Catering Food and Drink Supplier",
  "Catering service",
  "Cathedral",
  " Catholic cathedral",
  " Catholic church",
  " Catholic school",
  "Cattery",
  "Cattle Farm",
  "Cattle Market",
  " CBSE school",
  " CD store",
  "Ceiling Supplier",
  "Cell Phone Accessory Store",
  "Cell Phone Store",
  "Cement Manufacturer",
  "Cement Supplier",
  "Cemetery",
  " Central American restaurant",
  "Central Authority",
  "Central Bank",
  "Ceramic Manufacturer",
  "Ceramics Wholesaler",
  "Certification Agency",
  "Certified Public Accountancy firm",
  "Chalet",
  "Chamber of Agriculture",
  "Chamber of Commerce",
  "Chamber of Handicrafts",
  "Champon Noodle Restaurant",
  "Chanko Restaurant",
  "Chapel",
  "Charcuterie",
  "Charity",
  "Charter School",
  "Chartered Accountant",
  "Check Cashing Service",
  "Cheese Manufacturer",
  "Cheese Shop",
  "Cheesesteak Restaurant",
  "Chemical Engineering firm",
  "Chemical Exporter",
  "Chemical Manufacturer",
  "Chemical Plant",
  "Chemical Wholesaler",
  "Chemistry Faculty",
  "Chemistry Lab",
  " Chesapeake restaurant",
  "Chess and Card Club",
  "Chess Club",
  " Chevrolet dealer",
  "Chicken Hatchery",
  "Chicken Restaurant",
  "Chicken Shop",
  "Chicken Wings Restaurant",
  "Child Care Agency",
  "Child Health Care Centre",
  "Child Psychologist’s",
  "Childbirth Class",
  "Children’s Amusement Center",
  "Children’s Hall",
  "Children’s Policlinic",
  "Childrens’s Book Store",
  "Children’s Cafe",
  "Children’s Clothing Store",
  "Children’s Club",
  "Children’s Farm",
  "Children’s Furniture Store",
  "Children’s Home",
  "Children’s Hospital",
  "Children’s Library",
  "Children’s Museum",
  "Children’s Party Buffet provider",
  "Children’s Party Service",
  "Children’s Store",
  "Children’s Theater",
  " Chilean restaurant",
  "Chimney Service",
  "Chimney Sweep service",
  "Chinaware Store",
  " Chinese language school",
  " Chinese medical hospital",
  " Chinese medicine clinic",
  " Chinese medicine store",
  " Chinese noodle restaurant",
  " Chinese pastry restaurant",
  " Chinese restaurant",
  " Chinese supermarket",
  " Chinese takeaway",
  " Chinese tea house",
  "Chiropractic clinic",
  "Artisanal Chocolate kitchen",
  "Chocolate Cafe",
  "Chocolate Factory",
  "Chocolate Shop",
  "Chophouse Restaurant",
  " Christian book store",
  " Christian church",
  " Christian college",
  " Christmas market",
  " Christmas store",
  " Christmas tree farm",
  " Chrysler dealer",
  "Church",
  " Church of Christ",
  " Church of Jesus Christ of Latter-day Saints",
  " Church of the Nazarene",
  "Church Supply Store",
  "Churreria",
  "Cider Bar",
  "Cider Mill",
  "Cigar Shop",
  "Cinema Equipment Supplier",
  "Circular Distribution Service",
  "Circus",
  "Citizen Information Bureau",
  "Citizen’s Advice Bureau",
  "City Administration office",
  "City Clerk’s Office",
  "City Courthouse",
  "City Department of Environment",
  "City Department of Public Safety",
  "City Department of Transportation",
  "City District Office",
  "City Employment Department",
  "City Government Office",
  "City or Town Hall",
  "City Hospital",
  "City Park",
  "City pillar shrine",
  "City Tax Office",
  "Civic Center",
  "Civil Defence agency",
  "Civil Engineering Company",
  "Civil Examinations Academy",
  "Civil Law Attorney",
  "Civil Police office",
  "Civil Registry",
  "Classified Ads Newspaper Publisher",
  "Cleaners",
  "Cleaning Products Supplier",
  "Cleaning Service",
  "Clock Repair Service",
  "Clock Maker’s",
  "Closed Circuit Television firm",
  "Clothes and Fabric Manufacturer",
  "Clothes and Fabric Wholesaler",
  "Clothes Market",
  "Clothing Alteration Service",
  "Clothing Store",
  "Clothing Supplier",
  "Clothing Wholesale Market Place",
  "Clothing Wholesaler",
  "Club",
  " CNG fitment center",
  "Coaching Center",
  "Coal Exporter",
  "Coal Supplier",
  "Coalfield",
  "Coast Guard Station",
  "Coat Wholesaler",
  "Cocktail Bar",
  "Co-ed School",
  "Coffee Machine Supplier",
  "Coffee Roastery",
  "Coffee Shop",
  "Coffee Store",
  "Coffee Vending Machine",
  "Coffee Wholesaler",
  "Coffin Supplier",
  "Coin Dealer",
  "Coin-Operated Laundry Equipment Supplier",
  "Coin-Operated Locker service",
  "Cold Cut Store",
  "Cold Noodle Restaurant",
  "Cold Storage Facility",
  "Collectibles Store",
  "College",
  "College of Agriculture",
  " Colombian restaurant",
  "Comedy Club",
  "Comic Book Store",
  "Comic Cafe",
  "Commercial Agent",
  "Commercial Cleaning Service",
  "Commercial Printer",
  "Commercial Real Estate Agency",
  "Commercial Real Estate Inspector",
  "Commercial Refrigeration service",
  "Commercial Refrigerator Supplier",
  "Commissioner for Oaths",
  "Community Center",
  "Community College",
  "Community Garden",
  "Community Health Centre",
  "Community School",
  "Company Registry",
  "Computer Accessories Store",
  "Computer Club",
  "Computer Consultancy firm",
  "Computer Desk Store",
  "Computer Hardware Manufacturer",
  "Computer Networking Center",
  "Computer Repair Service",
  "Computer Security Service",
  "Computer Service",
  "Computer Software Store",
  "Computer Store",
  "Computer Support and Services",
  "Computer Training School",
  "Computer Wholesaler",
  "Concert Hall",
  "Concrete Contractor",
  "Concrete Factory",
  "Concrete Metal Framework Supplier",
  "Concrete Product Supplier",
  "Condiments Supplier",
  "Condominium Complex",
  "Condominium Rental Agency",
  "Confectionery store",
  "Confectionery Wholesaler",
  "Conference Center",
  "Conference Hotel",
  "Conservation Department",
  "Conservative Club",
  "Conservative Synagogue",
  "Conservatory Construction Contractor",
  "Conservatory of Music",
  "Conservatory Supply and Installation firm",
  "Consignment Shop",
  "Construction and Maintenance Office",
  "Construction Company",
  "Construction Equipment Supplier",
  "Construction Machine Dealer",
  "Construction Machine Rental Service",
  "Construction Material Wholesaler",
  "Consultancy firm",
  "Consumer Advice Center",
  "Contact Lens Supplier",
  "Container Service",
  "Container Supplier",
  "Container Terminal",
  "Containers Supplier",
  " contemporary Louisiana restaurant",
  "Continental Restaurant",
  "Convenience Store",
  "Convenience Store Organization",
  "Convention Center",
  "Convention Information Bureau",
  "Conveyancer",
  "Cookie Shop",
  "Cooking School",
  "Cooling Plant",
  "Copier Repair Service",
  "Copper Supplier",
  "Coppersmith",
  "Copy Shop",
  "Copying Supply Store",
  "Corporate Campus",
  "Corporate Entertainment Service",
  "Corporate Gift Supplier",
  "Corporate Office",
  "Correctional Services Department",
  "Cosmetic Dentist’s",
  "Cosmetic Products Manufacturer",
  "Cosmetics and Perfumes Supplier",
  "Cosmetics Store",
  "Cosmetics Wholesaler",
  "Cosplay Cafe",
  " Costa Rican restaurant",
  "Costume Jewelry Shop",
  "Costume Rental Service",
  "Costume Store",
  "Cottage",
  "Cottage Rental service",
  "Cottage Village",
  "Cotton Exporter",
  "Cotton Mill",
  "Cotton Supplier",
  "Counseling service",
  "Countertop Store",
  "Country Club",
  "Country Food Restaurant",
  "Country House",
  "Country Park",
  "County Government Office",
  "Courier Service",
  "Surfing school",
  "Court Executive Officer",
  "Court Reporting service",
  "Couscous Restaurant",
  "Couture Store",
  "Co-working Space",
  "Crab House",
  "Craft Centre",
  "Craft Store",
  "Cramming School",
  "Crane Dealer",
  "Crane Rental Agency",
  "Crane Service",
  "Craniosacral Therapist’s",
  "Creche",
  "Credit Counseling Service",
  "Credit Reporting Agency",
  "Credit Union",
  "Cremation Service",
  " Creole restaurant",
  "Crêperie",
  "Cricket Club",
  "Cricket Ground",
  "Cricket Shop",
  "Crime Victim Service",
  "Criminal Justice Attorney",
  " Croatian restaurant",
  "Crop Grower",
  "Croquet Club",
  "Cruise Agency",
  "Cruise Line Company",
  "Cruise Terminal",
  "Crushed Stone Supplier",
  " Cuban restaurant",
  "Culinary School",
  "Cultural Association",
  "Cultural Center",
  "Cupcake Shop",
  "Cured Ham Bar",
  "Cured Ham Store",
  "Cured Ham Warehouse",
  "Curling Club",
  "Curling Hall",
  "Currency Exchange Service",
  "Curtain and Upholstery Cleaning Service",
  "Curtain Store",
  "Curtain Supplier and Maker",
  "Custom Confiscated Goods Store",
  "Custom Home Builder",
  "Custom Label Printer",
  "Custom T-shirt Store",
  "Custom Tailor",
  "Customs Broker",
  "Customs Consultant",
  "Customs Department",
  "Customs Office",
  "Customs Warehouse",
  "Cutlery Store",
  "Cycling Park",
  " Czech restaurant",
  "Dairy",
  "Dairy Farm",
  "Dairy Farm Equipment Supplier",
  "Dairy Store",
  "Dairy Supplier",
  "Dan Dan Noodle Restaurant",
  "Dance Club",
  "Dance Company",
  "Dance Conservatory",
  "Dance Hall",
  "Dance Pavillion",
  "Dance Restaurant",
  "Dance School",
  "Dance Store",
  " Danish restaurant",
  "Darts Bar",
  "Darts Supply Store",
  "Data Entry Service",
  "Data Recovery Service",
  "Database Management Company",
  "Dating Service",
  "Day Care Center",
  "Day Spa",
  "Deaf Church",
  "Deaf School",
  "Deaf Service",
  "Debris Removal Service",
  "Debt Collection Agency",
  "Decal Supplier",
  "Deck Builder",
  "Deli",
  " delivery Chinese restaurant",
  "Delivery Service",
  "Demolition Contractor",
  "Jeans Shop",
  "Dental Clinic",
  "Dental Hygienist’s",
  "Dental Implant Periodontist’s",
  "Dental Insurance Agency",
  "Dental Laboratory",
  "Dental Radiology",
  "Dental School",
  "Dental Supply Store",
  "Dentist’s",
  "Denture Care Center",
  "Department for Regional Development",
  "Department of Education",
  "Department of Finance",
  "Department of Housing",
  "Department of Motor Vehicles",
  "Department of Public Safety",
  "Department of Social Services",
  "Department of Transportation",
  "Department Store",
  "Dept of City Treasure",
  "Dept of State Treasure",
  "Dermatologist’s",
  "Desalination Plant",
  "Design Agency",
  "Design Engineering firm",
  "Design Institute",
  "Desktop Publishing Service",
  "Sweets and Dessert Buffet",
  "Dessert Restaurant",
  "Dessert Shop",
  "Detective agency",
  "Detention Center",
  "Diabetes Center",
  "Diabetes Equipment Supplier",
  "Diabetologist’s",
  "Diagnostic Center",
  "Dialysis Center",
  "Diamond Buyer",
  "Diamond Dealer",
  "Diaper Service",
  "Diesel Engine Dealer",
  "Diesel Engine Repair Service",
  "Diesel Fuel Supplier",
  "Digital Printer",
  "Digital Printing Service",
  "Dim Sum Restaurant",
  "Diner",
  "Dinner Theater",
  "Direct Mail Advertising firm",
  "Dirt Supplier",
  "Disability Equipment Supplier",
  "Disability Services and Support Organisation",
  "Disabled Sports Center",
  "Disc Golf Course",
  " Disciples of Christ church",
  "Disco Club",
  "Discount Store",
  "Discount Supermarket",
  "Display Home Centre",
  "Display Stand Manufacturer",
  "Disposable Tableware Supplier",
  "Distance Learning Center",
  "Distillery",
  "Distribution Service",
  "District Attorney",
  "District Council",
  "District Government Office",
  "District Justice",
  "District Office",
  "Dive Bar",
  "Dive Club",
  "Diving Shop",
  "Diving Center",
  "Diving Contractor",
  "Divorce Lawyer",
  "Divorce Service",
  " DJ service",
  " DJ supply store",
  "Do-it-Yourself Shop",
  "Dock Builder",
  "Doctor’s office",
  " Dodge dealer",
  "Dog Breeder",
  "Dog Cafe",
  "Dog Day Care Center",
  "Dog Hostel",
  "Dog Park",
  "Dog Trainer’s",
  "Dog Walker’s",
  "Dogsled Ride Service",
  "Dojo Restaurant",
  "Doll Restoration Service",
  "Doll Store",
  "Dollar Store",
  "Domestic Abuse Treatment Center",
  "Domestic Airport",
  " Dominican restaurant",
  "Donations Center",
  "Donut Shop",
  "Door Manufacturer",
  "Door Shop",
  "Door Supplier",
  "Door Warehouse",
  "Double Glazing Installer",
  "Down Home Cooking Restaurant",
  "Drafting Equipment Supplier",
  "Drafting Service",
  "Drainage Service",
  "Drama School",
  "Drawing school",
  "Dress and Tuxedo Rental Service",
  "Dress Store",
  "Dressmaker",
  "Dried Flower Shop",
  "Dried Seafood Store",
  "Drilling Contractor",
  "Drilling Equipment Supplier",
  "Drinking Water Fountain",
  "Drive-in Movie Theater",
  "Driver and Vehicle Licensing Agency",
  "Driver’s License Office",
  "Drivers License Training School",
  "Driveshaft Shop",
  "Driving School",
  "Driving Test Centre",
  "Drug Addiction Treatment Center",
  "Drug Testing Service",
  "Drug Store",
  "Drumming School",
  "Drum Store",
  "Dry Cleaner’s",
  "Dry Fruit Store",
  "Dry Ice Supplier",
  "Dry Wall Contractor",
  "Dry Wall Supply Store",
  " Ducati dealer",
  "Dude Ranch",
  "Dump Truck Dealer",
  "Dump Truck Service",
  "Dumpling Restaurant",
  " Dutch restaurant",
  "Duty-Free Store",
  " DVD store",
  "Dye Store",
  "Dyeworks",
  "Dynamometer Supplier",
  "E-Commerce Agency",
  "E-commerce Service",
  "Ear-Piercing Service",
  "Earth Works Company",
  " East African restaurant",
  " Eastern European restaurant",
  " Eastern Orthodox church",
  "Eating Disorder Treatment Center",
  "Eclectic Restaurant",
  "Ecological Park",
  "Ecologists Association",
  "Economic Consultant",
  "Economic Development Agency",
  " Ecuadorian restaurant",
  "Education Center",
  "Educational Consultant",
  "Educational Institution",
  "Educational Supply Store",
  "Educational Testing Service",
  " EFTPOS equipment supplier",
  "Egg Supplier",
  " Egyptian restaurant",
  "Elder Law Attorney’s office",
  "Electric Motor Repair Shop",
  "Electric Motor Store",
  "Electric Utility Company",
  "Electric Utility Manufacturer",
  "Electric Vehicle Charging Station",
  "Electrical Appliance Wholesaler",
  "Electrical Engineering firm",
  "Electrical Equipment Supplier",
  "Electrical Installation Service",
  "Electrical Repair Shop",
  "Electrical Substation",
  "Electrical Supply Store",
  "Electrical Wholesaler",
  "Electrician firm",
  "Electrolysis Hair Removal Service",
  "Electronic Engineering firm",
  "Electronic Parts Supplier",
  "Electronics Accessories Wholesaler",
  "Electronics Company",
  "Electronics Engineering firm",
  "Electronics Exporter",
  "Electronics Hire Shop",
  "Electronics Manufacturer",
  "Electronics Repair Shop",
  "Electronics Store",
  "Electronics Vending Machine",
  "Electronics Wholesaler",
  "Elementary School",
  "Elevator Manufacturer",
  "Elevator Service",
  "Embassy",
  "Embossing Service",
  "Embroidery Service",
  "Embroidery Shop",
  "Emergency Call Booth",
  "Emergency Care Physician",
  "Emergency Care Service",
  "Emergency Dental Service",
  "Emergency Locksmith Service",
  "Emergency Management Ministry",
  "Emergency Room",
  "Emergency Training School",
  "Emergency Veterinarian Service",
  "Employment Agency",
  "Employment Attorney",
  "Employment Center",
  "Employment Consultant",
  "Employment Search Service",
  "Endocrinologist’s office",
  "Endodontist’s office",
  "Endoscopy clinic",
  "Energy Equipment and Solutions",
  "Energy Supplier",
  "Engine Rebuilding Service",
  "Engineering firm",
  "Engineering Consultant",
  "Engineering School",
  " English language camp",
  " English language school",
  " English restaurant",
  "Engraver’s",
  "Entertainment Agency",
  "Envelope Supplier",
  "Environment Office",
  "Environment Renewable Natural Resources",
  "Environmental Consultant",
  "Environmental Engineer",
  "Environmental Health Service",
  "Environmental Organization",
  "Environmental Protection Organization",
  " Episcopal church",
  "Equestrian Club",
  "Equestrian Facility",
  "Equestrian Resort",
  "Equestrian Store",
  "Equipment Exporter",
  "Equipment Importer",
  "Equipment Rental Agency",
  "Equipment Supplier",
  " Eritrean restaurant",
  "Erotic Massage parlor",
  "Escrow Service",
  "Espresso Bar",
  "Estate Appraisal service",
  "Estate Liquidator",
  "Estate Planning Attorney’s office",
  " Ethiopian restaurant",
  "Ethnic Restaurant",
  "Ethnographic Museum",
  " European restaurant",
  "Evangelical Church",
  "Evening Dress Rental Service",
  "Evening School",
  "Event Management Company",
  "Event Planner’s",
  "Event Technology Service",
  "Event Ticket Seller",
  "Event Venue",
  "Excavating Contractor",
  "Executive Search Firm",
  "Executive Suite Rental Agency",
  "Executor’s office",
  "Exhibit",
  "Exhibition and Trade Centre",
  "Exhibition Planner’s",
  "Exporter’s office",
  "Extended Stay Hotel",
  "Eye Care Center",
  "Fabric Product Manufacturer",
  "Fabric Store",
  "Fabric Wholesaler",
  "Fabrication Engineer",
  "Facial Spa",
  "Factory Equipment Supplier",
  "Faculty of Arts",
  "Faculty of Law",
  "Faculty of Pharmacy",
  "Faculty of Psychology",
  "Faculty of Science",
  "Faculty of Sports",
  "Fair Trade Organization",
  "Fairground",
  "Falafel Restaurant",
  "Family Counselor",
  "Family Day Care Service",
  "Family Hotel",
  "Family Law Attorney",
  "Family Planning Center",
  "Family Planning Counselor’s office",
  "Family Practice Physician’s office",
  "Family Restaurant",
  "Family Service Center",
  "Farm",
  "Farm Bureau",
  "Farm Equipment Repair Service",
  "Farm Equipment Supplier",
  "Farm School",
  "Farm Shop",
  "Farmers’ Market",
  "Farmstay",
  "Fashion Accessories Store",
  "Fashion Design School",
  "Fashion Designer",
  "Fast Food Restaurant",
  "Fastener Supplier",
  "Favela",
  "Fax Service",
  "Federal Agency for Technical Relief",
  "Federal Credit Union",
  "Federal Government Office",
  "Federal Police office",
  "Federal Reserve Bank",
  "Feed Manufacturer",
  "Animal Feed Store",
  "Felt Boots Store",
  "Fence Contractor",
  "Fence Supply Store",
  "Fencing Salon",
  "Fencing School",
  "Feng Shui Consultant",
  "Feng Shui Shop",
  "Ferris wheel",
  "Ferry Service",
  "Fertility Clinic",
  "Fertility Physician’s office",
  "Fertilizer Supplier",
  "Festival",
  "Festival Hall",
  " Fiat dealer",
  "Fiber Optic Products Supplier",
  "Fiberglass Repair Service",
  "Fiberglass Supplier",
  "Figurine Shop",
  " Filipino restaurant",
  "Film and Photograph Library",
  "Film Production Company",
  "Filtration Plant",
  "Finance Broker’s office",
  "Financial Auditing firm",
  "Financial Consultant",
  "Financial Institution",
  "Financial Planning service",
  "Fine Dining Restaurant",
  "Fingerprinting Service",
  "Finishing Materials Supplier",
  " Finnish restaurant",
  "Fire Alarm Supplier",
  "Fire Damage Restoration Service",
  "Fire Department Equipment Supplier",
  "Fire Fighters’ Academy",
  "Fire Protection Consultant",
  "Fire Protection Equipment Supplier",
  "Fire Protection Service",
  "Fire Protection System Supplier",
  "Fire Station",
  "Firearms Academy",
  "Fireplace Manufacturer",
  "Fireplace Store",
  "Firewood Supplier",
  "Fireworks Store",
  "Fireworks Supplier",
  "First Aid Station",
  "Fish and Chips Restaurant",
  "Fish and Chips Takeaway",
  "Fish Farm",
  "Fish Processinging plant",
  "Fish Spa",
  "Fish Store",
  "Fishing Camp",
  "Fishing Charter",
  "Fishing Club",
  "Fishing Pier",
  "Fishing Pond",
  "Fishing Store",
  "Health Club",
  "Exercise Equipment Store",
  "Fitness Equipment Wholesaler",
  "Fitted Furniture Supplier",
  "Flag Store",
  "Flamenco Dance Store",
  "Flamenco School",
  "Flamenco Theater",
  "Flavours, Fragrances and Aroma Supplier",
  "Flea Market",
  "Flight School",
  "Floating Market",
  "Floor Refinishing Service",
  "Floor Sanding and Polishing Service",
  "Flooring Contractor",
  "Flooring Store",
  " Floridian restaurant",
  "Florist’s",
  "Flour Mill",
  "Flower Delivery service",
  "Flower Designer’s",
  "Flower Market",
  " FMCG goods wholesaler",
  " FMCG manufacturer",
  "Foam Rubber Producer",
  "Foam Rubber Supplier",
  "Folk High School",
  "Fondue Restaurant",
  "Food and Beverage Consultant’s",
  "Food and Beverage Exporter",
  "Food Bank",
  "Food Broker",
  "Food Court",
  "Food Machinery Supplier",
  "Food Manufacturer",
  "Food Manufacturing Supply",
  "Food Processing Company",
  "Food Processing Equipment",
  "Food Producer",
  "Food Products Supplier",
  "Food Seasoning Manufacturer",
  "Foot Bath",
  "Foot Care center",
  "Foot Massage Parlor",
  "Football Club",
  " American football field",
  " Ford dealer",
  "Foreclosure Service",
  "Foreign Consulate",
  "Foreign Exchange Students Organization",
  "Foreign Languages Program School",
  "Foreign Trade Consultant",
  "Foreman Builders’ Association",
  "Forensic Consultant’s",
  "Forestry Service",
  "Forklift Dealer",
  "Forklift Rental Service",
  "Formal Wear Store",
  "Fortress",
  "Fortune Telling Service",
  "Foster Care Service",
  "Foundation",
  "Foundry",
  "Fountain Contractor",
  " Foursquare church",
  "Fraternal Organization",
  "Free Clinic",
  "Free Parking Lot",
  "Freestyle Wrestling space",
  "Freight Forwarding Service",
  " French language school",
  " French restaurant",
  " French steakhouse restaurant",
  "Fresh Food Market",
  "Fried Chicken Takeaway",
  " Friends church",
  "Frituur",
  "Frozen Dessert Supplier",
  "Frozen Food Manufacturer",
  "Frozen Food Store",
  "Frozen Yogurt Shop",
  "Fruit and Vegetable Processing plant",
  "Fruit and Vegetable Store",
  "Fruit and Vegetable Wholesaler",
  "Fruit Parlor",
  "Fruit Wholesaler",
  "Fruits Wholesaler",
  " Fu Jian restaurant",
  "Fuel Supplier",
  "Fugu Restaurant",
  "Full Dress Rental Service",
  " Full Gospel church",
  "Function Room Facility",
  "Fund Management Company",
  "Funeral Director’s",
  "Funeral Home",
  "Fur Coat Shop",
  "Fur Manufacturer",
  "Fur Service",
  "Furnace Parts Supplier",
  "Furnace Repair Service",
  "Furnace Store",
  "Furnished Apartment Building",
  "Furniture Accessories",
  "Furniture Accessories Supplier",
  "Furniture Maker’s",
  "Furniture Manufacturer",
  "Furniture Rental Service",
  "Furniture Repair Shop",
  "Furniture Store",
  "Furniture Wholesaler",
  "Fusion Restaurant",
  "Futon Store",
  "Futsal Court",
  " Galician restaurant",
  "Gambling House",
  "Gambling Instructor’s",
  "Game Store",
  "Garage Builder",
  "Garage Door Supplier",
  "Garbage Collection Service",
  "Garbage Dump",
  "Garbage Dump Service",
  "Garden",
  "Garden Building Supplier",
  "Garden Center",
  "Garden Furniture Shop",
  "Garden Machinery Supplier",
  "Gardener",
  "Garment Exporter",
  "Gas Company",
  "Gas Cylinders Supplier",
  "Gas Engineering firm",
  "Gas Installation Service",
  "Gas Logs Supplier",
  "Gas Shop",
  "Gas Station",
  "Gasfitter",
  "Gasket Manufacturer",
  "Gastroenterologist’s office",
  "Gastrointestinal surgery clinic",
  "Gastropub",
  "Gay and Lesbian Organization",
  "Gay Bar",
  "Gay Night Club",
  "Gay Sauna",
  "Gazebo Builder",
  "Gemologist’s office",
  "Genealogy service",
  "General Contractor",
  "General Hospital",
  "General Practice Attorney",
  "General Practitioner",
  "General Register Office",
  "General Store",
  "Generator Shop",
  "Geography and History Faculty",
  "Geological Research Company",
  "Geological Service",
  "Geologist’s",
  " Georgian restaurant",
  "Geotechnical Engineering firm",
  " German language school",
  " German restaurant",
  "Ghost Town",
  "Gift Basket Store",
  "Gift Shop",
  "Gift Wrap Store",
  "Girl Bar",
  "Girls’ High School",
  "Glass and Mirror Shop",
  "Glass Block Supplier",
  "Glass Blower’s",
  "Glass Cutting Service",
  "Glass Engravery",
  "Glass Etching Service",
  "Glass Manufacturer",
  "Glass Merchant",
  "Glass Repair Service",
  "Glass Shop",
  "Glassware Manufacturer",
  "Glassware Store",
  "Glassware Wholesaler",
  "Glazier’s",
  "Gluten-Free Restaurant",
  " GMC dealer",
  "Go-Kart Track",
  "Gold Dealership",
  "Gold Mine",
  "Goldfish Store",
  "Goldsmith’s",
  "Golf Cart Dealer",
  "Golf Club",
  "Golf Course",
  "Golf Course Builder’s",
  "Golf Driving Range",
  "Golf Instructor’s",
  "Golf Resort",
  " Gospel church",
  "Gourmet Grocery Store",
  "Government College",
  "Government Economic Program",
  "Government Hospital",
  "Government Office",
  "Government School",
  " GPS supplier",
  "Graduate School",
  "Graffiti Removal Service",
  "Grain Elevator",
  "Grammar School",
  "Grand Cafe",
  "Grande École",
  "Granite Supplier",
  "Graphic Design firm",
  "Gravel Pit",
  "Gravel Plant",
  "Greco—Roman Wrestling space",
  " Greek Orthodox church",
  " Greek restaurant",
  "Green Energy Supplier",
  "Greengrocer’s",
  "Greenhouse",
  "Greeting Card Shop",
  "Greyhound Stadium",
  "Grill Store",
  "Grocery Delivery Service",
  "Grocery Store",
  "Group Accommodation unit",
  "Group Home",
  " Guatemalan restaurant",
  "Guest House",
  " Gui Zhou restaurant",
  "Guitar school",
  "Guitar Store",
  "Gun Club",
  "Gun Shop",
  "Offal Barbecue Restaurant",
  "Gutter Cleaning Service",
  "Gym",
  "Gymnasium School",
  "Gymnastics Center",
  "Gymnastics Club",
  "Obstetrician’s office",
  "Gypsum Product Supplier",
  "Gyros Restaurant",
  "Haberdashery",
  "Hair Extension Technician’s",
  "Hair Extensions Supplier",
  "Hair Removal Service",
  "Hair Replacement Service",
  "Hair Salon",
  "Hair Transplantation Clinic",
  " Haitian restaurant",
  " Hakka restaurant",
  "Halal Restaurant",
  "Halfway House",
  "Ham Shop",
  "Hamburger Restaurant",
  "Hammam",
  "Hand Surgeon",
  "Handbag Shop",
  "Handball Club",
  "Handball Court",
  "Handicapped Transportation Service",
  "Handicraft center",
  "Handicraft Exporter",
  "Handicraft Fair",
  "Handicraft Museum",
  "Handicraft School",
  "Handicrafts Wholesaler",
  "Handyman firm",
  "Hang-Gliding Center",
  "Hardware Store",
  "Hardware Training Institute",
  " Harley-Davidson dealer",
  "Hat Shop",
  "Haunted House",
  "Haute Couture Fashion House",
  " haute French restaurant",
  " Hawaiian goods store",
  " Hawaiian restaurant",
  "Hawker Centre",
  "Hawker Stall",
  "Hay Supplier",
  "Head Start Center",
  "Health and Beauty Shop",
  "Health Consultant",
  "Health Food Restaurant",
  "Health Food Store",
  "Health Insurance Agency",
  "Health Resort",
  "Health Spa",
  "Hearing Aid Repair Service",
  "Hearing Aid Store",
  "Heart Hospital",
  "Heating Contractor",
  "Heating Equipment Supplier",
  "Heating Oil Supplier",
  "Helicopter Charter",
  "Helicopter Tour Agency",
  "Heliport",
  "Helium Gas Supplier",
  "Helpline",
  "Hematology clinic",
  "Herb Shop",
  "Herbal Medicine Store",
  "Herbalist’s",
  "Heritage Building",
  "Heritage Museum",
  "Heritage Preservation organization",
  "High Ropes school",
  "High School",
  "Higher Secondary School",
  "Highway Patrol office",
  "Hiking Area",
  " Hindu temple",
  "Hip Hop Dance Class",
  " Hispanic church",
  "Historical Landmark",
  "Historical Place Museum",
  "Historical Society",
  "History Museum",
  " HIV testing center",
  "Hoagie Restaurant",
  "Hobby Store",
  "Hockey Club",
  "Hockey Field",
  "Hockey Rink",
  "Hockey Supply Store",
  "Holding Company",
  "Holiday Accommodation Service",
  "Holiday Home",
  "Holiday Park",
  "Holistic Medicine Practitioner’s",
  "Home Automation Company",
  "Home Builder",
  "Home Cinema Installation firm",
  "Home Goods Store",
  "Home Hairdressing service",
  "Home Health Care Service",
  "Home Help service",
  "Home Help Service Agency",
  "Home Improvement Store",
  "Home Inspector",
  "Home Insurance Agency",
  "Home Theater Store",
  "Homekill Service",
  "Homeless Service",
  "Homeless Shelter",
  "Homeopath’s",
  "Homeopathic Pharmacy",
  "Homeowners’ Association",
  " Honda dealer",
  " Honduran restaurant",
  "Honey Farm",
  " Hong Kong–style fast food restaurant",
  "Hookah Bar",
  "Hookah Store",
  "Horse Boarding Stable",
  "Horse Breeder’s",
  "Horse Rental Service",
  "Horse Riding Field",
  "Horse Riding School",
  "Horse Trailer Dealer",
  "Horse Trainer",
  "Horseback Riding Service",
  "Horse Transport Supplier",
  "Horseshoe Smith",
  "Horsestable Studfarm",
  "Hose Supplier",
  "Hospice",
  "Hospital",
  "Hospital Equipment and Supplies service",
  "Hospital Department",
  "Hospitality and Tourism School",
  "Hospitality High School",
  "Host Club",
  "Hostel",
  "Hot Bedstone Spa",
  "Hot Dog Restaurant",
  "Hot Dog Stand",
  "Hot Pot Restaurant",
  "Hot Spring Hotel",
  "Hot Tub Repair Service",
  "Hot Tub Store",
  "Hot Water System Supplier",
  "Hotel",
  "Hotel Management School",
  "Hotel Supply Store",
  "House Cleaning Service",
  "House Clearance Service",
  "House Sitting service",
  "House Sitter Agency",
  "Houseboat Rental Service",
  "Household Chemicals Supplier",
  "Household Goods Wholesaler",
  "Housing Association",
  "Housing Authority",
  "Housing Complex",
  "Housing Cooperative",
  "Housing Development",
  "Housing Society",
  "Housing Utility Company",
  "Hub Cap Supplier",
  "Huissier",
  "Human Resource Consulting agency",
  " Hunan restaurant",
  " Hungarian restaurant",
  "Hunting and Fishing Store",
  "Hunting Area",
  "Hunting Club",
  "Hunting Preserve",
  "Hunting Store",
  " HVAC contractor",
  "Hydraulic Engineering firm",
  "Hydraulic Equipment Supplier",
  "Hydraulic Repair Service",
  "Hydroelectric Power Plant",
  "Hydroponics Equipment Supplier",
  "Hygiene Articles Wholesaler",
  "Hygiene Station",
  "Hypermarket",
  "Hypnotherapy Service",
  " Hyundai dealer",
  "Ice Cream Equipment Supplier",
  "Ice Cream Shop",
  "Ice Hockey Club",
  "Ice Skating Club",
  "Ice Skating Class",
  "Ice Skating Rink",
  "Ice Supplier",
  " Icelandic restaurant",
  " ICSE School",
  "Idol Manufacturer",
  "Image Consultant’s",
  "IMAC Theater",
  "Immigration and Naturalization Service",
  "Immigration Attorney’s office",
  "Immigration Detention Centre",
  "Immunology center",
  "Impermeabilization Service",
  "Import Export Company",
  "Import service",
  "Incense Supplier",
  "Incineration Plant",
  "Income Protection Insurance agency",
  "Income Tax Help Association",
  " Indian grocery store",
  " Indian Muslim restaurant",
  " Indian restaurant",
  " Indonesian restaurant",
  "Indoor Cycling arena",
  "Indoor Golf Course",
  "Indoor Playground",
  "Indoor Snowcenter",
  "Indoor Swimming Pool",
  "Industrial Area",
  "Industrial Chemicals Wholesaler",
  "Industrial Consulting firm",
  "Industrial Design Company",
  "Industrial Door Supplier",
  "Industrial Engineering firm",
  "Industrial Engineers Association",
  "Industrial Equipment Supplier",
  "Industrial Framework Supplier",
  "Industrial Gas Supplier",
  "Industrial Real Estate Agency",
  "Industrial Supermarket",
  "Industrial Technical Engineers Association",
  "Industrial Vacuum Equipment Supplier",
  "Infectious Disease clinic",
  " Infiniti dealer",
  "Information Bureau",
  "Information Service",
  "Inn",
  "Insolvency Service",
  "Institute of Geography and Statistics",
  "Instrumentation Engineering firm",
  "Insulation Contracting firm",
  "Insulation Materials Store",
  "Insulator Supplier",
  "Insurance Agency",
  "Insurance Attorney’s office",
  "Insurance Broker’s office",
  "Insurance Company",
  "Insurance School",
  "Intellectual Property Registry",
  "Interior Architect’s Office",
  "Interior Construction Contractor",
  "Interior Designer’s",
  "Interior Door supplier",
  "Interior Fitting Contracting firm",
  "Interior Plant Service",
  "Internal Medicine Ward",
  "International Airport",
  "International School",
  "International Trade Consulting firm",
  "Internet Cafe",
  "Internet Marketing Service",
  "Internet Service Provider",
  "Internet Shop",
  "Internist’s clinic",
  "Investment Bank",
  "Investment Company",
  "Investment Service",
  "Invitation Printing Service",
  " Irish goods store",
  " Irish pub",
  " Irish restaurant",
  "Iron and Steel Contracting firm",
  "Iron Ware Dealership",
  "Iron Works",
  "Irrigation Equipment Supplier",
  " Israeli restaurant",
  " Isuzu dealer",
  " Italian grocery store",
  " Italian restaurant",
  "Institute of Technology",
  " Jaguar dealer",
  " Jain temple",
  " Jamaican restaurant",
  "Janitorial Equipment Supplier",
  "Janitorial Service",
  " authentic Japanese restaurant",
  " Japanese cheap sweets shop",
  " Japanese confectionary shop",
  " Japanese curry restaurant",
  " Japanese delicatessen",
  " Japanese grocery Store",
  "Ryotei Restaurant",
  " Japanese hot pot restaurant",
  " Japanese inn with hot spring",
  " Japanese inn",
  "Izakaya Restaurant",
  " Japanese language school",
  " Japanese regional restaurant",
  " Japanese restaurant",
  " Japanese steakhouse",
  " Japanese sweets restaurant",
  " Japanized western restaurant",
  "Jazz Club",
  " Jeep dealer",
  " Jehovah’s Witness Kingdom Hall",
  "Jeweler’s",
  "Jewelry Appraiser",
  "Jewelry Buyer",
  "Jewelry Designer’s",
  "Jewelry Engraver’s",
  "Jewelry Equipment Supplier",
  "Jewelry Exporter",
  "Jewellery Manufacturer",
  "Jewelry Repair Service",
  "Jewelry Store",
  " Jewish restaurant",
  " Jiang Su restaurant",
  "Joiner’s",
  "Judicial Auction house",
  "Judicial Scrivener’s office",
  "Judo Club",
  "Judo School",
  "Juice Shop",
  "Jujitsu School",
  "Junior College",
  "Junk Dealer",
  "Junk Store",
  "Junkyard",
  "Justice Department",
  "Jute Exporter",
  "Jute Mill",
  "Juvenile Detention Center",
  "Kabaddi Club",
  "Kaiseki Restaurant",
  "Karaoke restaurant",
  "Karaoke Bar",
  "Karaoke Equipment Rental Service",
  "Karate Club",
  "Karate School",
  " Kashmiri restaurant",
  " Kawasaki motorcycle dealer",
  " Kazakhstani restaurant",
  "Kebab Shop",
  "Kennel",
  "Kerosene Supplier",
  "Key Duplication Service",
  " Kia dealer",
  "Kickboxing School",
  "Kilt Shop and Hire service",
  "Kimono Store",
  "Kindergarten",
  "Kinesiologist’s office",
  "Kiosk",
  "Kitchen Furniture Store",
  "Kitchen Remodeler",
  "Kitchen Supply Store",
  "Kite Shop",
  "Knife Manufacturing company",
  "Knife Store",
  "Knit Shop",
  "Knitting school",
  "Knitwear Manufacturer",
  " Korean barbecue restaurant",
  " Korean beef restaurant",
  " Korean church",
  " Korean grocery Store",
  " Korean restaurant",
  " Korean rib restaurant",
  "Kosher Grocery Store",
  "Kosher Restaurant",
  "Kung Fu School",
  "Kushiyaki Restaurant",
  " Kyoto-style Japanese restaurant",
  "Labor Relations Attorney’s office",
  "Labor Union",
  "Laboratory",
  "Laboratory Equipment Supplier",
  "Labour Club",
  "Ladder Supplier",
  "Laminating Equipment Supplier",
  "Lamination Service",
  "Lamp Repair Service",
  "Lamp Shade Supplier",
  "Allotment",
  "Land Planning Authority",
  "Land Reform Institute",
  " Land Rover dealer",
  "Land Surveying Office",
  "Land Surveyor’s office",
  "Landscape Architect",
  "Landscape Designer",
  "Landscape Lighting Designer",
  "Landscaping service",
  "Landscaping Supply Store",
  "Language School",
  " Laotian restaurant",
  "Lapidary",
  "Laser Cutting Service",
  "Laser Equipment Supplier",
  "Laser Hair Removal Service",
  "Laser Tag Center",
  " LASIK surgeon",
  " Latin American restaurant",
  "Laundromat",
  "Laundry",
  "Laundry Service",
  "Law Book Store",
  "Law Firm",
  "Law Library",
  "Law School",
  "Lawn Bowls Club",
  "Lawn Care Service",
  "Lawn Equipment Rental Service",
  "Lawn Irrigation Equipment Supplier",
  "Lawn Mower Repair Service",
  "Lawn Mower Store",
  "Lawn Sprinkler System Contractor",
  "Lawyer’s office",
  "Lawyers’ Association",
  "Leagues Club",
  "Learner Driver Training Area",
  "Learning Center",
  "Leasing Service",
  "Leather Cleaning Service",
  "Leather Coats Store",
  "Leather Exporter",
  "Leather Goods Manufacturer",
  "Leather Goods Store",
  "Leather Goods Supplier",
  "Leather Goods Wholesaler",
  "Leather Repair Service",
  "Leather Wholesaler",
  " Lebanese restaurant",
  "Legal Affairs Bureau",
  "Legal Aid Office",
  "Legal Services",
  "Leisure Centre",
  " Lexus dealer",
  "Library",
  "License Bureau",
  "License Plate Frames Supplier",
  "Lido",
  "Life Coach service",
  "Life Insurance Agency",
  "Light Bulb Supplier",
  "Lighting Consultant",
  "Lighting Contractor",
  "Lighting Manufacturer",
  "Lighting Store",
  "Lighting Wholesaler",
  "Limousine Service",
  " Lincoln Mercury dealer",
  "Line Marking Service",
  "Linen Store",
  "Lingerie Manufacturer",
  "Lingerie Store",
  "Lingerie Wholesaler",
  "Linoleum Store",
  "Lion Dance Troupe business",
  "Liquidator’s",
  "Liquor Store",
  "Off-license",
  "Liquor Wholesaler",
  "Literacy Program",
  " Lithuanian restaurant",
  "Little League Club",
  "Little League Field",
  "Live Music Bar",
  "Live Music Venue",
  "Livery Company",
  "Livestock Auction House",
  "Livestock Breeder",
  "Livestock Dealer",
  "Livestock Producer",
  "Loan provider’s",
  "Lobster Restaurant",
  "Local Government Office",
  "Local History Museum",
  "Local Medical Services",
  "Lock Supplier",
  "Locksmith’s",
  "Lodge",
  "Log Cabin provider",
  "Log Home Builder",
  "Logging Contractor",
  "Logistics Service",
  "Loss Adjuster’s",
  "Lost Property Office",
  "Lottery Retailer",
  "Lottery Shop",
  "Lounge",
  "Love Hotel",
  "Low Emission Zone",
  "Low Income Housing Program",
  " LPG conversion service",
  "Luggage Repair Service",
  "Luggage Store",
  "Luggage Wholesaler",
  "Lumber Store",
  "Lunch Restaurant",
  " Lutheran church",
  "Luxury Hotel",
  "Lyceum",
  "Lymph Drainage Therapist’s",
  "Machine Construction service",
  "Machine Knife Supplier",
  "Machine Maintenance service",
  "Machine Repair Service",
  "Machine Shop",
  "Machine Workshop",
  "Machinery Parts Manufacturer",
  "Machining Manufacturer",
  "Macrobiotic Restaurant",
  " Madrilian restaurant",
  "Magazine Publisher",
  "Magazine Store",
  "Magic Store",
  "Magician’s",
  "Mah Jong House",
  "Mailbox Rental Service",
  "Mailbox Supplier",
  "Mailing Machine Supplier",
  "Mailing Service",
  "Customs Office",
  "Make-up Artist’s",
  " Malaysian restaurant",
  "Male Hospital",
  " Maltese restaurant",
  "Mammography Service",
  "Management School",
  " Mandarin restaurant",
  "Manor House",
  "Manufactured Home Transporter service",
  "Manufacturer",
  " Maori organization",
  "Map Store",
  "Mapping Service",
  "Marae",
  "Marble Contractor",
  "Marble Supplier",
  " Marche restaurant",
  "Marina",
  "Marine Engineering firm",
  "Marine Self-Defense Force base",
  "Marine Supply Store",
  "Marine Surveyor",
  "Maritime Museum",
  "Market",
  "Market Operator service",
  "Market Researcher service",
  "Marketing Agency",
  "Marketing Consultancy",
  "Marquee Hire Service",
  "Marriage party organizer",
  "Marriage Counselor’s",
  "Marriage License Bureau",
  "Martial Arts Club",
  "Martial Arts School",
  "Martial Arts Supply Store",
  " Masonic lodge",
  "Masonry Contractor’s",
  "Masonry Supply Store",
  "Massage School",
  "Massage Spa",
  "Massage Supply Store",
  "Massage Therapist’s",
  "Match Box Manufacturer",
  "Material Handling Equipment Supplier",
  "Maternity Hospital",
  "Maternity Store",
  "Mathematics School",
  "Mattress Store",
  "Mausoleum construction service",
  " Mazda dealer",
  "Meal Delivery service",
  "Meal Takeaway service",
  "Measuring Instruments Supplier",
  "Meat Packing service",
  "Meat Processing plant",
  "Meat Product provider",
  "Meat Dish Restaurant",
  "Meat Wholesaler",
  "Mechanic’s",
  "Mechanical Contracting firm",
  "Mechanical Engineering firm",
  "Mechanical Plant",
  "Media and Information Sciences Faculty",
  "Media Company",
  "Media Consulting firm",
  "Media House",
  "Mediation Service",
  "Medical Billing Service",
  "Medical Book Store",
  "Medical Center",
  "Medical Certificate Service",
  "Medical Clinic",
  "Medical Diagnostic Imaging Center",
  "Medical Equipment Manufacturer",
  "Medical Equipment Supplier",
  "Medical Examiner’s",
  "Medical Group",
  "Medical Laboratory",
  "Medical Office",
  "Medical School",
  "Medical Spa",
  "Medical Supply Store",
  "Medical Technology Manufacturer",
  "Medical Transcription Service",
  "Medicine Exporter",
  "Meditation Center",
  "Meditation Instructor’s",
  " Mediterranean restaurant",
  "Meeting Planning Service",
  " Mehndi class",
  " Mehndi designer’s",
  "Memorial Estate",
  "Memorial Park",
  " Mennonite church",
  "Men’s Clothing Store",
  "Men’s Tailor",
  "Mental Health Clinic",
  "Mental Health Service",
  "Mercantile Development",
  " Mercedes Benz dealer",
  " Messianic synagogue",
  "Metal Construction Company",
  "Metal-Detecting Equipment Supplier",
  "Metal Fabricator",
  "Metal Finishing service",
  "Metal Heat Treating Service",
  "Metal Industry Suppliers",
  "Metal Machinery Supplier",
  "Metal Polishing Service",
  "Metal Processing Company",
  "Metal Stamping Service",
  "Metal Supplier",
  "Metal Working Shop",
  "Metal Workshop",
  "Metallurgy Company",
  "Metalware Dealer",
  "Metalware Producer",
  "Metaphysical Supply Store",
  " Methodist church",
  "Metropolitan Train Company",
  " Mexican goods store",
  " Mexican grocery store",
  " Mexican restaurant",
  "Microbiology center",
  "Microwave Oven Repair Service",
  " mid-Atlantic restaurant",
  " Middle Eastern restaurant",
  "Middle School",
  "Midwife service",
  "Military Archive",
  "Military Residence",
  "Military Barracks",
  "Military Base",
  "Military Cemetery",
  "Military Hospital",
  "Military Recruiting Office",
  "Military School",
  "Military Town",
  "Milk Delivery Service",
  "Mill",
  "Millwork Shop",
  "Mine",
  "Mineral Water Company",
  "Mineral Water Wholesaler",
  "Miniature Golf Course",
  "Miniatures Store",
  "Minibus Taxi Service",
  "Mining Company",
  "Mining Consultancy",
  "Mining Engineering firm",
  "Mining Equipment supplier",
  "Ministry of Education",
  "Mirror Shop",
  "Miso Cutlet Restaurant",
  "Missing Persons Organization",
  "Mission",
  " Mitsubishi dealer",
  "Mobile Caterer",
  "Mobile Disco",
  "Mobile Hairdresser’s",
  "Mobile Home Dealer",
  "Mobile Home Park",
  "Mobile Home Rental Agency",
  "Mobile Home Supply Store",
  "Mobile Money Agent",
  "Mobile Network Operator",
  "Mobile Phone Repair Shop",
  "Mobility Equipment Supplier",
  "Model Car Play Area",
  "Model Design Company",
  "Model Portfolio Studio",
  "Model Train Store",
  "Modeling Agency",
  "Modeling School",
  "Modern Art Museum",
  " modern British restaurant",
  " modern European restaurant",
  " modern French restaurant",
  "Modular Home Builder",
  "Modular Home Dealer",
  "Mold Maker",
  "Molding Supplier",
  "Monastery",
  "Money Order Service",
  "Money Transfer Service",
  " Mongolian barbecue restaurant",
  "Monjayaki Restaurant",
  "Monogramming Service",
  " Montessori school",
  "Monument Maker",
  "Moped Dealer",
  " Moravian church",
  "Modern Izakaya Restaurant",
  " Moroccan restaurant",
  "Mortgage Broker’s",
  "Mortgage Lender’s",
  "Mortuary",
  "Mosque",
  "Motel",
  "Motor Scooter Dealer",
  "Motor Scooter Repair Shop",
  "Motor Vehicle Dealer",
  "Motorcycle Dealer",
  "Motorcycle Driving School",
  "Motorcycle Insurance Agency",
  "Motorcycle Parts Store",
  "Motorcycle Rental Agency",
  "Motorcycle Repair Shop",
  "Motorcycle Shop",
  "Motoring Club",
  "Motorsports Store",
  "Mountain Cable Car",
  "Mountain Cabin",
  "Mountaineering Class",
  "Movie Rental Kiosk",
  "Movie Rental Store",
  "Movie Studio",
  "Movie Theater",
  "Moving and Storage Service",
  "Moving Company",
  "Moving Supply Store",
  " MRI center",
  " Muay Thai boxing gym",
  "Muffler Shop",
  "Mulch Supplier",
  "Multimedia and Electronic Book Publisher",
  "Municipal Administration Office",
  "Municipal Corporation",
  "Municipal Department Agricultural Development",
  "Municipal Department Agriculture Food Supply",
  "Municipal Department Civil Defense",
  "Municipal Department Communication",
  "Municipal Department Finance",
  "Municipal Department Housing and Urban Development",
  "Municipal Department of Culture",
  "Municipal Department of Sports",
  "Municipal Department of Tourism",
  "Municipal Department Science Technology",
  "Municipal Department Social Defense",
  "Municipal Guard headquarters",
  "Municipal Health Department",
  "Municipal Office Education",
  "Municipal Social Development",
  "Museum",
  "Museum of Space History",
  "Museum of Zoology",
  "Music Box Store",
  "Music College",
  "Music Conservatory",
  "Music Instructor",
  "Music Management and Promotion service",
  "Music Production company",
  "Music Publisher",
  "Music School",
  "Music Store",
  "Musical Club",
  "Musical Instrument Manufacturer",
  "Musical Instrument Rental Service",
  "Musical Instrument Repair Shop",
  "Musical Instrument Store",
  "Mutton Barbecue Restaurant",
  "Nail Salon",
  "Nanny service",
  "Nanotechnology Engineering firm",
  "National Forest",
  "National Health Foundation",
  "National Library",
  "National Museum",
  "National Park",
  "National Reserve",
  " Native American goods store",
  " Native American restaurant",
  "Natural Foods Store",
  "Natural Gas Supplier",
  "Natural History Museum",
  "Natural Stone Exporter",
  "Natural Stone Supplier",
  "Natural Stone Wholesaler",
  "Nature Preserve",
  "Naturopathic Practitioner’s",
  "Naval Base",
  " Navarraise restaurant",
  " Neapolitan restaurant",
  "Needlework Shop",
  "Neon Sign Shop",
  "Neonatal Physician’s office",
  " Nepalese restaurant",
  "Nephrologist’s",
  "Netball Club",
  "Neurology clinic",
  "Neurosurgery center",
  " New Age church",
  " New England restaurant",
  "New Year’s Tree Market",
  " New Zealand restaurant",
  "News Service",
  "Newspaper Advertising Department",
  "Newspaper Distributor",
  "Newspaper Publisher",
  "Newsstand",
  " Nicaraguan restaurant",
  "Night Club",
  "Night Market",
  " Nissan dealer",
  "Non-Denominational Church",
  "Non-Governmental Organization",
  "Non-Profit Organization",
  "Non-Smoking Holiday Home",
  "Noodle Shop",
  " North African restaurant",
  " northern Italian restaurant",
  " Norwegian restaurant",
  "Notary Association",
  "Public Notary office",
  "Notions Store",
  "Novelties Wholesaler",
  "Novelty Store",
  "Nuclear Engineering firm",
  "Nuclear Power Company",
  "Nuclear Power Plant",
  "Nudist Club",
  "Nudist Park",
  " Nuevo Latino restaurant",
  "Numerologist’s",
  "Convent",
  "Nursery School",
  "Nursing Agency",
  "Nursing Association",
  "Nursing Home",
  "Nursing School",
  "Nut Store",
  "Nutritionist’s",
  "Nyonya Restaurant",
  "Obanzai Restaurant",
  "Observation Deck",
  "Observatory",
  "Women’s Health Clinic",
  "Occupational Health Service",
  "Occupational Medical Physician",
  "Occupational Safety and Health service",
  "Occupational Therapist’s",
  "Oden Restaurant",
  "Off-road Race Track",
  "Off-Roading Area",
  "Off-Track Betting Shop",
  "Offal Pot Restaurant",
  "Office Accessories Wholesaler",
  "Office Equipment Rental Service",
  "Office Equipment Repair Service",
  "Office Equipment Supplier",
  "Office Furniture Store",
  "Office of Vital Records",
  "Office Refurbishment Service",
  "Office Space Rental Agency",
  "Office Supply Store",
  "Office Supply Wholesaler",
  "Oil and Gas Exploration Service",
  "Oil Change Service",
  "Oil and Natural Gas Company",
  "Oil Field Equipment Supplier",
  "Oil Refinery",
  "Oil Store",
  "Oil Wholesaler",
  "Oilfield",
  "Okonomiyaki Restaurant",
  " Oldsmobile dealer",
  "Olive Oil Bottling Company",
  "Olive Oil Cooperative",
  "Olive Oil Manufacturer",
  "Oncology clinic",
  " Opel dealer",
  "Open-Air Museum",
  "Open University",
  "Opera Company",
  "Opera House",
  "Ophthalmologist’s",
  "Ophthalmology Clinic",
  "Optical Products Manufacturer",
  "Optical Wholesaler",
  "Optician’s",
  "Optometrist’s",
  "Oral Surgery clinic",
  "Orchard",
  "Concert hall",
  "Orchid Farm",
  "Orchid farm",
  "Organ Donation and Tissue Bank",
  "Organic Drug Store",
  "Organic Farm",
  "Organic Food Store",
  "Organic Restaurant",
  "Organic Shop",
  "Oriental Art Museum",
  "Oriental Goods Store",
  "Oriental Medicine Clinic",
  "Oriental Medicine Store",
  "Oriental Rug Store",
  "Orphan Asylum",
  "Orphanage",
  "Orthodontist’s",
  " Orthodox church",
  " Orthodox synagogue",
  "Orthopedic Clinic",
  "Orthopedic Shoe Store",
  "Orthopedic Surgery practice",
  "Orthoptist’s",
  "Orthotics and Prosthetics Service",
  "Osteopath’s",
  "Otolaryngologist’s",
  "Otolaryngology Clinic",
  "Otolaryngology Hospital",
  "Outboard Motor Store",
  "Outdoor Activity Organiser",
  "Outdoor Bath",
  "Outdoor Clothing and Equipment Shop",
  "Outdoor Equestrian Facility",
  "Outdoor Furniture Store",
  "Outdoor movie theater",
  "Outdoor Sports Store",
  "Outdoor Swimming Pool",
  "Outerwear Store",
  "Outlet Mall",
  "Outlet Store",
  "Oxygen Cocktail Spot",
  "Oxygen Equipment Supplier",
  "Oyster Bar Restaurant",
  "Oyster Supplier",
  "Pachinko Parlor",
  " Pacific Rim restaurant",
  "Packaging Company",
  "Packaging Machinery",
  "Packaging Supply Store",
  "Padel Club",
  "Padel Court",
  "Pagoda",
  "Pain Control Clinic",
  "Pain Management Physician’s",
  "Paint Manufacturer",
  "Paint Store",
  "Paint-Stripping Company",
  "Paintball Center",
  "Paintball Store",
  "Painting service",
  "Painting school",
  "Painting Studio",
  "Paintings Store",
  " Pakistani restaurant",
  "Pallet Supplier",
  " pan-Asian restaurant",
  " pan-Latin restaurant",
  "Pancake Restaurant",
  "Paper Bag Supplier",
  "Paper Distributor",
  "Paper Exporter",
  "Paper Mill",
  "Paper Shredding Machine Supplier",
  "Paper Store",
  " Paraguayan restaurant",
  "Paralegal Services Provider",
  "Parasailing Ride Service",
  "Parish church",
  "Park",
  "Park and Ride",
  "Parking Garage",
  "Parking Lot",
  "Parking Lot for Bicycles",
  "Parking Lot for Motorcycles",
  "Parkour Spot",
  "Parochial School",
  " Parsi temple",
  "Part-Time Daycare service",
  "Party Equipment Rental Service",
  "Party Planner’s",
  "Party Store",
  "Passport Agency",
  "Passport Office",
  "Passport Photo Processor",
  "Pasta Shop",
  "Pastry Shop",
  "Patent Attorney’s office",
  "Patent Office",
  "Paternity Testing Service",
  "Pathologist’s",
  "Patients Support Association",
  "Patio Enclosure Supplier",
  "Patisserie",
  "Paving Contracting firm",
  "Paving Materials Supplier",
  "Pawn Shop",
  "Payphone",
  "Payroll Service",
  "Public Call Office Booth",
  "Pedestrian Zone",
  "Pediatric Cardiologist’s",
  "Pediatric Dentist’s",
  "Pediatric Ophthalmologist’s",
  "Pediatric practice",
  "Pen Store",
  " Pennsylvania Dutch restaurant",
  "Pension Office",
  " Pentecostal church",
  "People’s House",
  "Performing Arts center",
  "Performing Arts Theater",
  "Perfume Store",
  "Perinatal Center",
  "Periodontist’s",
  "Permanent Make-up Clinic",
  " Persian restaurant",
  "Personal Injury Attorney’s office",
  "Personal Trainer’s",
  " Peruvian restaurant",
  "Pest Control Service",
  "Pet Adoption Service",
  "Pet Boarding Service",
  "Pet Cemetery",
  "Pet-Friendly Accommodation provider",
  "Pet Funeral Service",
  "Pet Groomer",
  "Pet Moving Service",
  "Pet Sitting service",
  "Pet Store",
  "Pet Supply Store",
  "Pet Training service",
  "Petrochemical Engineering firm",
  "Petroleum Products Company",
  "Pharmaceutical Company",
  "Pharmaceutical Lab",
  "Pharmaceutical Products Wholesaler",
  "Pharmacy",
  "Philharmonic Hall",
  "Pho Restaurant",
  "Phone Repair Service",
  "Photo Agency",
  "Photo Lab",
  "Photo Restoration Service",
  "Photo Shop",
  "Photocopier Supplier",
  "Photography Class",
  "Photography School",
  "Photography Service",
  "Photography Studio",
  "Physiatrist’s",
  "Physical Examination Center",
  "Physician Referral Service",
  "Physical Therapist’s",
  "Physical Therapy Clinic",
  "Physiotherapy Equipment Supplier",
  "Piano Bar",
  "Piano school",
  "Piano Maker",
  "Piano Moving Service",
  "Piano Repair Service",
  "Piano Store",
  "Piano-Tuning Service",
  "Pick Your Own Farm Produce service",
  "Picnic Ground",
  "Picture Frame Renovating and Restoring Service",
  "Picture Frame Shop",
  "Pie Shop",
  "Pilates Studio",
  "Pile Driver service",
  "Pilgrimage Place",
  "Pinata Supplier",
  "Pinball Machine Supplier",
  "Pine Furniture Shop",
  "Pipe Supplier",
  "Pizza Delivery service",
  "Pizza Restaurant",
  "Pizza Takeaway",
  "Planetarium",
  "Plant and Machinery Hire service",
  "Plant Nursery",
  "Plasterer’s",
  "Plastic Bag Supplier",
  "Plastic Bags Wholesaler",
  "Plastic Fabrication Company",
  "Plastic Injection Molding Service",
  "Plastic Products Supplier",
  "Plastic Resin Manufacturer",
  "Plastic Surgery Clinic",
  "Plastic Wholesaler",
  "Plating Service",
  "Play School",
  "Playground",
  "Playground Equipment Supplier",
  "Playgroup",
  "Plumbing service",
  "Plumbing Supply Store",
  "Plus-Size Clothing Store",
  "Plywood Supplier",
  "Pneumatic Tools Supplier",
  "Po’ Boy Restaurant",
  "Podiatrist’s",
  "Police Academy",
  "Police Supply Store",
  " Polish restaurant",
  "Political Party office",
  "Polo Club",
  "Polygraph Service",
  "Polymer Supplier",
  " Polynesian restaurant",
  "Polytechnic",
  "Polythene and Plastic Sheeting Supplier",
  "Pond Contracting service",
  "Pond Fish Supplier",
  "Pond Supply Store",
  " Pontiac dealer",
  "Pony Club",
  "Pony Ride Service",
  "Pool Academy",
  "Pool Billard Club",
  "Pool Cleaning Service",
  "Pool Hall",
  "Popcorn Store",
  "Katsudon Restaurant",
  "Porridge Restaurant",
  " Porsche dealer",
  "Port Authority",
  "Port Operating Company",
  "Portable Building Manufacturer",
  "Portable Toilet Supplier",
  "Portrait Studio",
  " Portuguese restaurant",
  "Post Office",
  "Poster Store",
  "Pottery Class",
  "Pottery Manufacturer",
  "Pottery Store",
  "Poultry Farm",
  "Poultry Store",
  "Powder Coating Service",
  "Power Station",
  "Power Plant Consultant",
  "Power Plant Equipment Supplier",
  "Prawn fishing company",
  "Pre-Gymnasium School",
  "Precision Engineering firm",
  "Prefabricated House Companies",
  "Prefecture office",
  " Japanese prefecture government office",
  "Pregnancy Care Center",
  "Preparatory School",
  " Presbyterian church",
  "Preschool",
  "Press Advisory service",
  "Pressure-Washing Service",
  "Pretzel Store",
  "Primary School",
  "Print Shop",
  "Printed Music Publisher",
  "Printer Ink Refill Store",
  "Printer Repair Service",
  "Printing Equipment and Supplies store",
  "Printing Equipment Supplier",
  "Prison",
  "Private College",
  "Private Equity Firm",
  "Private Golf Course",
  "Homestay provider",
  "Private Hospital",
  "Private Investigator’s",
  "Private School",
  "Private Sector Bank",
  "Private Tutoring service",
  "Private University",
  "Probation Office",
  "Process Server’s",
  "Proctologist’s",
  "Produce Market",
  "Produce Wholesaler",
  "Producteur de Champagne",
  "Producteur de Foie Gras",
  "Producteur d’Eau Minerale",
  "Professional and Hobby Association",
  "Professional Organizer",
  "Promenade",
  "Promotional Products Supplier",
  "Propane Supplier",
  "Propeller Shop",
  "Property Administrator",
  "Property Investment",
  "Property Maintenance firm",
  "Property Management Company",
  "Land Registry Office",
  "Prosthetics supplier",
  "Protective Clothing Supplier",
  " Protestant church",
  " Provence restaurant",
  "Provincial Council",
  "Psychiatric Hospital",
  "Psychiatrist’s office",
  "Psychic booth",
  "Psychoanalyst’s office",
  "Psychologist’s office",
  "Psychoneurological Specialized Clinic",
  "Psychopedagogy Clinic",
  "Psychosomatic Medical Practitioner",
  "Psychotherapist’s office",
  "Pub",
  "Public Amenity House",
  "Public Bath",
  "Public Bathroom",
  "Public Defender’s Office",
  "Public Female Bathroom",
  "Public Golf Course",
  "Public Health Department",
  "Public Housing agency",
  "Public Library",
  "Public Male Bathroom",
  "Public Medical Center",
  "Public Parking Space",
  "Public Prosecutor’s Office",
  "Public Relations Firm",
  "Public Safety Office",
  "Public Sauna",
  "Public School",
  "Public Sector Bank",
  "Public Swimming Pool",
  "Public University",
  "Public Webcam",
  "Public Wheelchair-Accessible Bathroom",
  "Public Works Department",
  "Publisher’s",
  " Puerto Rican restaurant",
  "Pulmonologist’s",
  "Pump Supplier",
  "Pumping Equipment and Service",
  "Pumpkin Patch",
  " Punjabi restaurant",
  "Puppet Theater",
  " PVC firm",
  " PVC windows supplier",
  "Quad-bike Rental Service",
  " Quaker church",
  "Quantity Surveyor’s",
  "Quarry",
  " Québécois restaurant",
  "Quilt Shop",
  "Race Car Dealer",
  "Racecourse",
  "Racing Car Parts Store",
  "Raclette Restaurant",
  "Racquetball Club",
  "Radiator Repair Service",
  "Radiator Shop",
  "Radio Broadcaster",
  "Radiologist’s",
  "Raft Trip Outfitter",
  "Rafting center",
  "Rail Museum",
  "Railing Contractor",
  "Railroad Company",
  "Railroad Contractor",
  "Railroad Equipment Supplier",
  "Railroad Ties Supplier",
  "Railway Service supplier",
  "Rainwater Tank Supplier",
  "Ramen Restaurant",
  "Ranch",
  "Rare Book Store",
  "Raw Food Restaurant",
  "Ready Mix Concrete Supplier",
  "Real Estate Agency",
  "Real Estate Agent’s",
  "Real Estate Appraisal service",
  "Real Estate Attorney’s office",
  "Real Estate Auction Firm",
  "Real Estate Consultancy",
  "Real Estate Developer’s",
  "Real Estate Fair",
  "Real Estate Rental Agency",
  "Real Estate School",
  "Real Estate Surveyor",
  "Reclamation Centre",
  "Record Company",
  "Records Storage Facility",
  "Record Store",
  "Recording Studio",
  "Recreation Center",
  "Recruiter’s",
  "Rectory",
  "Recycling Center",
  "Reenactment Site",
  "Reflexologist’s",
  " Reform synagogue",
  "Reformed Church",
  "Refrigerated Transport Service",
  "Refrigerator Repair Service",
  "Refrigerator Store",
  "Refugee Camp",
  "Regional Airport",
  "Regional Council office",
  "Regional Government Office",
  "Registered General Nurse’s office",
  "Registration Chamber",
  "Registration Office",
  "Registry Office",
  "Rehabilitation Center",
  "Reiki Therapist’s",
  "Religious Book Store",
  "Religious Destination",
  "Religious Goods Store",
  "Religious Institution",
  "Religious Organization",
  "Religious School",
  "Religious Seminary",
  "Remodelling agency",
  " Renault dealer",
  "Renters’ Insurance Agency",
  "Repair Service",
  "Reproductive Health Clinic",
  "Reptile Store",
  "Research and Product Development Firm",
  "Research Engineering firm",
  "Research Foundation",
  "Research Institute",
  "Resident Registration Office",
  "Residential College",
  "Residents’ Association",
  "Resort",
  "Rest Stop",
  "Restaurant",
  "Brasserie",
  "Restaurant Supply Store",
  "Resumé Service",
  "Retail Space Rental Agency",
  "Retaining Wall Supplier",
  "Retirement Community",
  "Retirement Home",
  "Retreat Center",
  "Rheumatologist’s",
  "Rice Cracker Shop",
  "Rice Mill",
  "Rice Restaurant",
  "Rice Shop",
  "Rice Wholesaler",
  "River Port",
  "Road Construction Company",
  "Road Construction Machine Repair Service",
  "Road Cycling shop",
  "Roads Ports and Canals Engineers Association",
  "Rock Climbing center",
  "Rock Climbing Gym",
  "Rock Climbing school",
  "Rock Landscaping Contractor",
  "Rock Music Club",
  "Rock Shop",
  "Rodeo",
  "Rolled Metal Products Supplier",
  "Roller Coaster",
  "Roller Skating Club",
  "Roller Skating Rink",
  " Roman restaurant",
  " Romanian restaurant",
  "Roofing Contractor",
  "Roofing Supply Store",
  "Roommate Referral Service",
  "Rowing Area",
  "Rowing Club",
  " RSL Club",
  "Rubber Products Supplier",
  "Rubber Stamp Store",
  "Rug Store",
  "Rugby Club",
  "Rugby Field",
  "Rugby League Club",
  "Rugby Store",
  "Running Store",
  " Russian Orthodox church",
  " Russian restaurant",
  "Rustic Furniture Store",
  " RV dealer",
  " RV park",
  "Recreational Vehicle Rental Agency",
  " RV repair shop",
  " RV storage facility",
  " RV supply store",
  " Saab dealer",
  "Saddlery",
  "Safe and Vault Shop",
  "Safety Equipment Supplier",
  "Sailing Club",
  "Sailing Event Area",
  "Sailing School",
  "Sailmaker",
  "Sake Brewery",
  "Salad Shop",
  "Salsa Bar",
  "Salsa Classes",
  " Salvadoran restaurant",
  "Salvage Dealer",
  "Salvage Yard",
  "Samba School",
  "Sambo School",
  "Sambodrome",
  "Sand and Gravel Supplier",
  "Sand Plant",
  "Sandblasting Service",
  "Sandwich Shop",
  "Sanitary Inspection",
  "Sanitation Service",
  "Satellite Communication Service",
  " Saturn dealer",
  "Sauna",
  "Sauna Club",
  "Sauna Store",
  "Savings Bank",
  "Saw Mill",
  "Saw Sharpening Service",
  "Scaffolding service",
  "Scaffolding Rental Service",
  "Scale Model Club",
  "Model Shop",
  "Scale Repair Service",
  "Scale Supplier",
  "Scandinavian Restaurant",
  "Scenic Spot",
  "School",
  "School Administrator",
  "School Bus Service",
  "School Center",
  "School District Office",
  "School For The Deaf",
  "School House",
  "School Lunch Center",
  "School Supply Store",
  "School Youth Hostel",
  "Science Academy",
  "Science Museum",
  "Scientific Equipment Supplier",
  "Scooter Rental Service",
  "Scooter Repair Shop",
  "Scout Hall",
  "Scout Home",
  "Scouting center",
  "Scrap Metal Dealer",
  "Scrapbooking Store",
  "Screen Printer",
  "Screen Printing Shop",
  "Screen Printing Supply Store",
  "Screen Repair Service",
  "Screen Store",
  "Screw Supplier",
  "scuba school",
  "scuba Tour Agency",
  "Sculpture Museum",
  "Donburi Seafood Restaurant",
  "Seafood Farm",
  "Seafood Market",
  "Seafood Restaurant",
  "Seafood Wholesaler",
  "Seal Shop",
  "Seaplane Base",
  "Seasonal Goods Store",
  "Second-Hand Store",
  "Security Guard Service",
  "Security Service",
  "Security System Installer",
  "Security System Supplier",
  "Seed Supplier",
  "Seitai massage parlor",
  "Self-Catering Accommodation provider",
  "Self-Defense School",
  "Self-Service Car Wash",
  "Self-Service Restaurant",
  "Self-Storage Facility",
  "Semi-Conductor Supplier",
  "Seminary",
  "Senior Citizen Center",
  "Aged Care center",
  "Senior High School",
  "Septic System Service",
  " Serbian restaurant",
  "Serviced Accommodation provider",
  " Seventh-Day Adventist church",
  "Sewage Disposal Service",
  "Sewage Treatment Plant",
  "Sewing Company",
  "Sewing Machine Repair Service",
  "Sewing Machine Store",
  "Sewing Shop",
  "Sexologist’s",
  " Seychelles restaurant",
  "Sukiyaki and Shabu Shabu Restaurant",
  "Shabu-shabu Restaurant",
  " Shan Dong restaurant",
  " Shanghainese restaurant",
  "Sharpening Service",
  "Shed construction firm",
  "Sheep Shearering service",
  "Sheepskin and Wool Products Supplier",
  "Sheepskin Coat Store",
  "Sheet Metal Contractor",
  "Sheet Music Store",
  "Shelter",
  "Sheltered Housing provider",
  "Shelving Store",
  "Sheriff’s Department",
  " Shinkin bank",
  " Shinto shrine",
  "Ship Builder’s",
  "Shipbuilding and Repair Company",
  "Shipping and Mailing Service",
  "Shipping Company",
  "Shipping Equipment Supplier",
  "Shipping Service",
  "Shipyard",
  "Shochu Brewery",
  "Shoe Factory",
  "Shoe Repair Shop",
  "Shoe-Shining Service",
  "Shoe Store",
  "Footwear Wholesaler",
  "Shogi school",
  "Shooting Event Area",
  "Shooting Range",
  "Supermarket Furniture Store",
  "Shopfitter agency",
  "Shopping Mall",
  "Short Term Apartment Rental Agency",
  "Shower Door Shop",
  "Shower Door Supplier",
  "Shredding Service",
  "Shrimp Farm",
  "Shrine",
  " Sichuan restaurant",
  " Sicilian restaurant",
  "Siding Contractor",
  "Sightseeing Tour Agency",
  "Sign Shop",
  "Gurudwara",
  "Silk Plant Shop",
  "Silk Store",
  "Silversmith’s",
  " Singaporean restaurant",
  "Singing Telegram Service",
  "Single-Sex Secondary School",
  "Singles Organization",
  "Sixth Form College",
  "Skate Sharpening Service",
  "Skate Shop",
  "Skateboard Park",
  "Skateboard Shop",
  "Skating School",
  "Skeet-Shooting Range",
  "Kushiage and Kushikatsu Restaurant",
  "Ski Club",
  "Ski Rental Service",
  "Ski Repair Service",
  "Ski Resort",
  "Ski School",
  "Ski Shop",
  "Skin Care Clinic",
  "Skin Care Products Vending Machine",
  "Skittle Alley",
  "Skittle Club",
  "Skydiving Center",
  "Skylight Contractor",
  "Slaughterhouse",
  "Sleep Clinic",
  "Small Appliance Repair Service",
  "Small Claims Assistance Service",
  "Small Engine Repair Service",
  "Small Plates Restaurant",
  "Smart Shop",
  "Smog Inspection Station",
  "Snack Bar",
  "Snow Removal Service",
  "Snowboard Rental Service",
  "Snowboard Shop",
  "Snowmobile Dealer",
  "Snowmobile Rental Service",
  "Soapland brothel",
  "Soba Noodle Shop",
  "Soccer Club",
  "Soccer Field",
  "Soccer Store",
  "Social Club",
  "Social Security Attorney’s office",
  "Social Security Financial Department",
  "Social Security Office",
  "Social Services Organization",
  "Social Welfare Center",
  "Social Worker’s office",
  "Société de Flocage",
  "Sod Supplier",
  "Sofa Store",
  "Soft Drinks Shop",
  "Suppon Restaurant",
  "Softball Club",
  "Softball Field",
  "Software Company",
  "Software Training Institute",
  "Soil Testing Service",
  " Sokol house",
  "Solar Energy Company",
  "Solar Energy Contractor",
  "Solar Energy Equipment Supplier",
  "Solar Hot Water System Supplier",
  "Solar Photovoltaic Power Plant",
  "Solid Fuel Company",
  "Solid Waste Engineer",
  "Soul Food Restaurant",
  "Soup Kitchen",
  "Soup Restaurant",
  "Soup Shop",
  " South African restaurant",
  " South American restaurant",
  " South Asian restaurant",
  " Southeast Asian restaurant",
  " southern Italian restaurant",
  "Southern Restaurant",
  " southwest France restaurant",
  "Southwestern Restaurant",
  "Souvenir Manufacturer",
  "Souvenir Store",
  "Soy Sauce Maker’s",
  "Spa",
  "Spa and Health Club",
  "Spa Garden",
  "Spa Resort",
  "Spa Town",
  " Spanish language school",
  " Spanish restaurant",
  "Special Education School",
  "Specialist Hospital",
  "Specialized Clinic",
  "Specialized hospital",
  "Speech Pathologist’s",
  "Sperm Bank",
  "Spice Store",
  "Spice Exporter",
  "Spice Wholesaler",
  " Spiritist center",
  "Sport Tour Agency",
  "Sporting Goods Store",
  "Sports Accessories Wholesaler",
  "Sports Bar",
  "Sports Card Store",
  "Sports Club",
  "Sports Complex",
  "Sports Equipment Rental Service",
  "Sports Massage Therapist’s",
  "Sports Medicine Clinic",
  "Sports Medicine Physician’s",
  "Sports Memorabilia Store",
  "Sports Nutrition Store",
  "Sports School",
  "Sportswear Store",
  "Sportwear Manufacturer",
  "Spring Supplier",
  "Squash Club",
  "Squash Court",
  " Sri Lankan restaurant",
  "Stable",
  "Stadium",
  "Stage",
  "Stage Lighting Equipment Supplier",
  "Stained Glass Studio",
  "Stainless Steel Plant",
  "Stair Contractor",
  "Stall Installation Service",
  "Stamp Collectors’ Club",
  "Stamp Shop",
  "Stand Bar",
  "Staple Food Package supplier",
  "State Archive",
  "State Department Agricultural Development",
  "State Department Agriculture Food Supply",
  "State Department Civil Defense",
  "State Department Communication",
  "State Department Finance",
  "State Department for Social Development",
  "State Department Housing and Urban Development",
  "State Department of Environment",
  "State Department of Tourism",
  "State Department of Transportation",
  "State Department Science Technology",
  "State Department Social Defense",
  "State Dept of Culture",
  "State Dept of Sports",
  "State Employment Department",
  "State Government Office",
  "State Liquor Store",
  "State Office of Education",
  "State Owned Farm",
  "State Park",
  "State Police",
  "State Social Development",
  "Stationery Manufacturer",
  "Stationery Store",
  "Stationery Wholesaler",
  "Statuary",
  " STD clinic",
  " STD testing service",
  "Steak House",
  "Steamboat Restaurant",
  "Steamed Bun Shop",
  "Steel Construction Company",
  "Steel Distributor",
  "Steel Drum Supplier",
  "Steel Erection firm",
  "Steel Fabricator",
  "Steel Framework Contractor",
  "Steelwork Design Company",
  "Steelwork Manufacturer",
  "Stereo Rental Store",
  "Stereo Repair Service",
  "Home Audio Store",
  "Sticker Manufacturer",
  "Stitching Class",
  "Stock Broker firm",
  "Stock Exchange Building",
  "Stone Carving service",
  "Stone Cutter’s",
  "Stone Supplier",
  "Storage Facility",
  "Store",
  "Store Equipment Supplier",
  "Stove Builder",
  "Stringed instrument maker",
  "Structural Engineering firm",
  "Stucco Contractor",
  "Student Career Counseling Office",
  "Student Dormitory",
  "Student Housing Center",
  "Student Union",
  "Student Parents Association",
  "Student Support Association",
  "Study at Home School",
  "Studying Center",
  "Stylist’s",
  " Subaru dealer",
  "Suburban Train Line",
  "Sugar Factory",
  "Sukiyaki Restaurant",
  "Summer Camp",
  "Summer Toboggan Run",
  "Sundae Restaurant",
  "Sunglasses Store",
  "Sunroom Contractor",
  "Super Public Bath",
  "Superannuation Consultancy",
  "Superfund Site",
  "Supermarket",
  "Surf Lifesaving Club",
  "Surf School",
  "Surf Shop",
  "Surgery office",
  "Surgical Center",
  "Surgical Products Wholesaler",
  "Surgical Supply Store",
  " Surinamese restaurant",
  "Surplus Store",
  "Surveyor’s",
  "Sushi Restaurant",
  " Suzuki dealer",
  " Suzuki motorcycle dealer",
  " Swedish restaurant",
  "Swiming Club",
  "Swimming hole",
  "Swimming Facility",
  "Swimming Lake",
  "Swimming Pool",
  "Swimming Pool Contractor",
  "Swimming Pool Repair Service",
  "Swimming Pool Supply Store",
  "Swimming School",
  "Swimwear Store",
  " Swiss restaurant",
  "Synagogue",
  "Synchronized Swimming class",
  " Syrian restaurant",
  "T-shirt Company",
  "T-shirt Store",
  "Table and Chair Rental Service",
  "Table Tennis Club",
  "Table Tennis Facility",
  "Table Tennis Supply Store",
  "Tack Shop",
  "Taco Restaurant",
  "Tae Kwon Do Comp Area",
  "Taekwondo School",
  "Tag Agency",
  "Tai Chi School",
  "Tailor",
  " Taiwanese restaurant",
  "Takoyaki Restaurant",
  "Talent Agency",
  "Tamale Shop",
  "Tannery",
  "Tanning Salon",
  " Taoist temple",
  "Tapas Bar",
  "Tapas Restaurant",
  "Tatami Store",
  "Tattoo and Piercing Shop",
  "Tattoo Removal Service",
  "Tattoo Shop",
  "Tax Assessor’s office",
  "Tax Attorney’s office",
  "Tax Collector’s Office",
  "Tax Consultancy",
  "Tax Department",
  "Tax Preparation Service",
  "Taxi Service",
  "Taxi Stand",
  "Taxidermist’s",
  " TB clinic",
  "Tea Exporter",
  "Tea House",
  "Tea Manufacturer",
  "Tea Market Place",
  "Tea Store",
  "Tea Wholesaler",
  "Teacher College",
  "Technical School",
  "Technical Service",
  "Technical University",
  "Technology Museum",
  "Technology Park",
  "Teeth-Whitening Service",
  "Telecommunication School",
  "Telecommunications Contractor",
  "Telecommunications Engineer",
  "Telecommunications Equipment Supplier",
  "Telecommunications Service Provider",
  "Telemarketing Service",
  "Telephone Answering Service",
  "Telephone Company",
  "Telephone Exchange",
  "Telescope Store",
  "Television Repair Service",
  "Television Station",
  "Temp Agency",
  "Tempura Donburi Restaurant",
  "Tempura Restaurant",
  "Tenant’s Union",
  "Tennis Club",
  "Tennis Court",
  "Tennis Court Construction Company",
  "Tennis school",
  "Tennis Store",
  "Tent Rental Service",
  "Teppanyaki Restaurant",
  " Tex-Mex restaurant",
  "Textile Engineering firm",
  "Textile Exporter",
  "Textile Mill",
  " Thai massage therapist’s",
  " Thai restaurant",
  "Theater Company",
  "Theater Supply Store",
  "Theatrical Costume Supplier",
  "Theme Park",
  "Thermal Bath",
  "Thermal Energy Company",
  "Thread Supplier",
  "Threads and Yarns Wholesaler",
  "Thrift Store",
  "Tile Contractor",
  "Tile Manufacturer",
  "Tile Store",
  "Time and Temperature Announcement Service",
  "Timeshare Agency",
  "Tyre Manufacturer",
  "Tire Shop",
  "Title Company",
  "Tobacco Exporter",
  "Tobacco Shop",
  "Tobacco Supplier",
  "Tofu Restaurant",
  "Tofu Shop",
  "Toiletries Store",
  "Toll Road Rest Stop",
  "Toll Booth",
  "Toner Cartridge Supplier",
  "Tongue Restaurant",
  "Tonkatsu Restaurant",
  "Tool and Die Shop",
  "Tool Grinding Service",
  "Tool Manufacturer",
  "Tool Rental Service",
  "Tool Repair Shop",
  "Tool Store",
  "Tool Wholesaler",
  "Toolroom",
  "Topography Company",
  "Topsoil Supplier",
  "Tour Agency",
  "Tour Operator",
  "Tourist Attraction",
  "Tourist Information Center",
  "Tower Communication Service",
  "Towing Equipment Provider",
  "Towing Service",
  "Townhouse Complex",
  "Toy and Game Manufacturer",
  "Toy Library",
  "Toy Manufacturer",
  "Toy Museum",
  "Toy Store",
  " Toyota dealer",
  "Tractor Dealer",
  "Tractor Equipment Supplier",
  "Tractor Repair Shop",
  "Trade Fair Construction Company",
  "Trade School",
  "Trading Card Store",
  "Traditional Costume Club",
  "Traditional Costume Store",
  "Traditional Market",
  "Traditional Restaurant",
  "Traditional Teahouse",
  " traditional American restaurant",
  "Traffic Office",
  "Traffic Police Station",
  "Trailer Dealer",
  "Trailer Hitch Supplier",
  "Trailer Manufacturer",
  "Trailer Rental Service",
  "Trailer Repair Shop",
  "Trailer Supply Store",
  "Train Repairing Center",
  "Train Ticket Agency",
  "Train Ticket Counter",
  "Train yard",
  "Training Centre",
  "Training School",
  "Transcription Service",
  "Translation bureau",
  "Transmission Shop",
  "Transportation Escort Service",
  "Transportation Service",
  "Travel Agency",
  "Travel Clinic",
  "Travellers’ Lodge",
  "Tree Farm",
  "Tree Service",
  "Trial Attorney’s office",
  "Tribal Headquarters",
  " Trinity church",
  " Triumph motorcycle dealer",
  "Trophy Shop",
  "Tropical Fish Store",
  "Truck Accessories Store",
  "Truck Dealer",
  "Truck Farmer",
  "Truck Parts Supplier",
  "Truck Rental Agency",
  "Truck Repair Shop",
  "Truck Stop",
  "Truck Topper Supplier",
  "Truck Wash",
  "Trucking Company",
  "Trucking School",
  "Truss Manufacturer",
  "Trust Bank",
  "Tune-Up Supplier",
  "Automobile Tuning service",
  " Tunisian restaurant",
  "Turf Supplier",
  " Turkish restaurant",
  " Turkmen restaurant",
  "Turnery",
  " Tuscan restaurant",
  "Tutoring Service",
  "Tuxedo Shop",
  "Typewriter Repair Service",
  "Typewriter Supplier",
  "Typing Service",
  "Udon Noodle Restaurant",
  " Ukrainian restaurant",
  "Unagi Restaurant",
  "Underwear Store",
  "Unemployment Insurance Consultancy",
  "Unemployment Office",
  "Unfinished Furniture Store",
  "Uniform Store",
  "Hairdresser’s",
  " Unitarian Universalist church",
  " United Church of Canada",
  " United Church of Christ",
  " United Methodist church",
  " United States armed forces base",
  " Unity church",
  "University",
  "University Department",
  "University Hospital",
  "University Library",
  "Upholstery Cleaning Service",
  "Upholstery Shop",
  "Urban Planning Department",
  "Urgent care center",
  "Urologist’s",
  "Urology Clinic",
  " Uruguayan restaurant",
  " Pacific Northwest restaurant",
  "Used Appliance Store",
  "Used Auto Parts Store",
  "Used Bicycle Shop",
  "Used Book Store",
  "Used Car Dealer",
  " used CD store",
  "Used Clothing Store",
  "Used Computer Store",
  "Used Furniture Store",
  "Used Game Store",
  "Used Motorcycle Dealer",
  "Used Musical Instrument Store",
  "Used Office Furniture Store",
  "Used Store Fixture Supplier",
  "Used Tire Shop",
  "Used Truck Dealer",
  "Utility Contractor",
  "Utility Trailer Dealer",
  " Uzbeki restaurant",
  "Holiday Apartment",
  "Vacation Home Rental Agency",
  "Vacuum Cleaner Repair Shop",
  "Vacuum Cleaner Store",
  "Vacuum Cleaning System Supplier",
  " Valencian restaurant",
  "Valet Parking Service",
  "Van Rental Agency",
  "Vaporizer Store",
  "Variety Store",
  "Vascular Surgery clinic",
  "Vastu Consultancy",
  " VCR repair service",
  "Vegan Restaurant",
  "Vegetable Wholesale Market",
  "Vegetable Wholesaler",
  "Vegetarian Cafe and Deli",
  "Vegetarian Restaurant",
  "Vehicle Examination Office",
  "Vehicle Exporter",
  "Vehicle Inspection",
  "Vehicle Shipping Agent",
  "Velodrome",
  "Vending Machine Supplier",
  "Venereologist’s",
  " Venetian restaurant",
  " Venezuelan restaurant",
  "Ventilating Equipment Manufacturer",
  "Venture Capital Company",
  "Veterans’ Affairs Department",
  "Veterans’ Center",
  "Veterans’ Hospital",
  "Veterans’ Organization",
  "Veterinary practice",
  "Veterinary Pharmacy",
  "Video Arcade",
  "Video Camera Repair Service",
  "Video Conferencing Equipment Supplier",
  "Video Conferencing Service",
  "Video Duplication Service",
  "Video Editing Service",
  "Video Equipment Repair Service",
  "Video Game Rental Kiosk",
  "Video Game Rental Service",
  "Video Game Rental Store",
  "Video Game Store",
  "Video Production Service",
  "Video Store",
  " Vietnamese restaurant",
  "Villa",
  "Village Hall",
  "Vineyard",
  " Vineyard church",
  "Vintage Clothing Store",
  "Violin Shop",
  "Virtual Office Rental",
  "Visa and Passport Office",
  "Visa Consultant",
  "Visitor Center",
  "Vitamin and Supplements Store",
  "Vocal school",
  "Vocational College",
  "Vocational School",
  " Volkswagen dealer",
  "Volleyball Club",
  "Volleyball Court",
  "Volleyball school",
  "Volunteer Organization",
  " Volvo dealer",
  "Voter Registration Office",
  "Voting Facility",
  " Waldorf kindergarten",
  " Waldorf school",
  "Walk-In Clinic",
  "Wallpaper Store",
  "War Museum",
  "Warehouse",
  "Warehouse club",
  "Warehouse store",
  "Washer and Dryer Repair Service",
  "Washer and Dryer Store",
  "Waste Management Service",
  "Watch Manufacturer",
  "Watch Repair Service",
  "Watch Store",
  "Water Cooler Supplier",
  "Water Damage Restoration Service",
  "Water Filter Supplier",
  "Water Jet Cutting Service",
  "Water Mill",
  "Water Park",
  "Water Polo Pool",
  "Water Pump Supplier",
  "Water Purification Company",
  "Water Ski Shop",
  "Water Skiing Club",
  "Water Skiing Instructor",
  "Water Skiing Service",
  "Water Softening Equipment Supplier",
  "Water Sports Equipment Rental Service",
  "Water Tank Cleaning Service",
  "Water Testing Service",
  "Water Treatment Plant",
  "Water Treatment Supplier",
  "Water Utility Company",
  "Water Works",
  "Water Works Equipment Supplier",
  "Waterbed Repair Service",
  "Waterbed Store",
  "Waterproofing Company",
  "Wax Museum",
  "Wax Supplier",
  "Waxing Hair Removal Service",
  "Weather Forecast Service",
  "Weaving Mill",
  "Web Hosting Company",
  "Website Designer",
  "Wedding Bakery",
  "Wedding Buffet service",
  "Wedding Chapel",
  "Wedding Dress Rental Service",
  "Wedding Photographer",
  "Wedding Planner’s",
  "Wedding Service",
  "Wedding Souvenir Shop",
  "Wedding Store",
  "Wedding Venue",
  "Weigh Station",
  "Weight Loss Service",
  "Weightlifting Area",
  "Weir",
  "Welder’s",
  "Welding Gas Supplier",
  "Welding Supply Store",
  "Well Drilling Contractor",
  "Wellness Center",
  "Wellness Hotel",
  "Wellness Program",
  " Welsh restaurant",
  " Wesleyan church",
  " West African restaurant",
  "Western Apparel Store",
  "Western Restaurant",
  "Whale-Watching Tour Agency",
  "Wheel-Alignment Service",
  "Wheel Store",
  "Wheelchair Rental Service",
  "Wheelchair Repair Service",
  "Wheelchair Store",
  "Wholesale Bakery",
  "Wholesale Drugstore",
  "Wholesale Florist’s",
  "Wholesale Food Store",
  "Wholesale Grocer’s",
  "Wholesale Jeweler’s",
  "Wholesale Market",
  "Wholesale Plant Nursery",
  "Wholesaler",
  "Wholesaler Household Appliances",
  "Wi-Fi Spot",
  "Wicker Store",
  "Wig Shop",
  "Wildlife and Safari Park",
  "Wildlife Park",
  "Wildlife Refuge",
  "Wildlife Rescue Service",
  "Willow Basket Manufacturer",
  "Wind Farm",
  "Wind Turbine manufacturer",
  "Window Cleaning Service",
  "Window Installation Service",
  "Window Supplier",
  "Window Tinting Service",
  "Window Treatment Store",
  "Windsurfing Store",
  "Wine Bar",
  "Wine Cellar",
  "Wine Club",
  "Wine Storage Facility",
  "Wine Store",
  "Wine Wholesaler and Importer",
  "Winemaking Supply Store",
  "Winery",
  " Wing Chun school",
  "Wok Restaurant",
  "Women’s Clothing Store",
  "Womens College",
  "Women’s Organization",
  "Women’s Protection Service",
  "Women’s Shelter",
  "Wood and Laminate Flooring Supplier",
  "Wood Floor Installation Service",
  "Wood Floor Refinishing Service",
  "Wood Frame Supplier",
  "Wood Stove Shop",
  "Wood Supplier",
  "Wood-Working school",
  "Woodworker’s",
  "Woodworking Supply Store",
  "Wool Store",
  "Work Clothes Store",
  "Workers’ Club",
  "Working Women’s Hostel",
  "Wrestling School",
  " X-ray equipment supplier",
  " X-ray lab",
  " Xiang cuisine restaurant",
  "Yacht Broker",
  "Yacht Club",
  "Yakatabune",
  "Yakiniku Restaurant",
  "Yakitori Restaurant",
  " Yamaha motorcycle dealer",
  "Yarn Store",
  " Yemenite restaurant",
  "Yeshiva",
  "Yoga school",
  "Yoga Retreat Center",
  "Yoga Studio",
  "Youth Care center",
  "Youth Center",
  "Youth Clothing Store",
  "Youth Club",
  "Youth Group",
  "Youth Hostel",
  "Youth Organization",
  "Youth Social Services Organization",
  " Zimbabwean restaurant",
  "Zoo"]

places = ["Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Central African Rep",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Democractic Republic of Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea North",
  "Korea South",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "St Kitts and Nevis",
  "St Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe"]